[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "dotmac-security"
version = "1.0.0"
description = "Comprehensive security services for DotMac Framework"
readme = "README.md"
requires-python = ">=3.11"
authors = [
    {name = "DotMac Framework", email = "dev@dotmac.framework"},
]
license = {text = "MIT"}
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]

dependencies = [
    "cryptography>=41.0.0",
    "pyjwt>=2.8.0",
    "bcrypt>=4.0.0",
    "python-multipart>=0.0.6",
    "pydantic>=2.0.0",
    "sqlalchemy>=2.0.0",
    "redis>=5.0.0",
    "structlog>=23.0.0",
    "fastapi>=0.104.0",
    "starlette>=0.27.0",
]

[project.optional-dependencies]
enterprise = [
    "ldap3>=2.9.0",
    "python-keycloak>=3.0.0",
    "oauthlib>=3.2.0",
]
dev = [
    "pytest>=7.0.0",
    "pytest-asyncio>=0.21.0",
    "pytest-cov>=4.0.0",
    "httpx>=0.24.0",
    "factory-boy>=3.3.0",
]

[project.urls]
Homepage = "https://github.com/dotmac/framework"
Documentation = "https://docs.dotmac.framework"
Repository = "https://github.com/dotmac/framework"
Issues = "https://github.com/dotmac/framework/issues"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"dotmac.security" = ["py.typed"]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py", "*_test.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
addopts = [
    "-v",
    "--strict-markers",
    "--strict-config",
    "--cov=dotmac.security",
    "--cov-report=term-missing",
    "--cov-report=html",
    "--cov-fail-under=90",
]
asyncio_mode = "auto"
markers = [
    "unit: marks tests as unit tests",
    "integration: marks tests as integration tests",
    "enterprise: marks tests requiring enterprise features",
]

[tool.coverage.run]
source = ["src/dotmac/security"]
omit = [
    "*/tests/*",
    "*/conftest.py",
    "*/__init__.py",
]

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "def __repr__",
    "raise AssertionError",
    "raise NotImplementedError",
    "if __name__ == .__main__.:",
]