[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "dotmac-networking"
version = "1.0.0"
description = "Comprehensive ISP networking package - IPAM, device automation, SNMP monitoring, RADIUS, and network protocols"
authors = ["DotMac Framework Team"]
license = "MIT"
readme = "README.md"
packages = [{include = "dotmac", from = "src"}]

[tool.poetry.dependencies]
python = ">=3.9,<4.0"
# Core foundation
dotmac-core = {path = "../dotmac-core", develop = true}
# Core dependencies
pydantic = "^2.5.0"
fastapi = ">=0.100.0"
sqlalchemy = "^2.0.0"
# Network protocols
httpx = "^0.25.0"
asyncssh = "^2.14.0"
# SNMP monitoring
pysnmp = "^5.0.0"
pysnmp-mibs = "^0.1.3"
# RADIUS authentication
pyrad = "^2.4"
# DNS and network utilities
dnspython = "^2.4.0"
netaddr = "^0.10.0"
ipaddress = {version = "^1.0.23", python = "<3.9"}
# Async utilities
aiofiles = "^23.2.1"
# VOLTHA integration (optional)
voltha-protos = {version = "^5.4.0", optional = true}
grpcio = {version = "^1.59.0", optional = true}
grpcio-tools = {version = "^1.59.0", optional = true}

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.0"
pytest-asyncio = "^0.21.0"
pytest-mock = "^3.12.0"
black = "^23.0.0"
isort = "^5.12.0"
ruff = "^0.1.0"
mypy = "^1.0.0"

[tool.poetry.extras]
voltha = ["voltha-protos", "grpcio", "grpcio-tools"]
all = ["voltha-protos", "grpcio", "grpcio-tools"]

[tool.ruff]
target-version = "py39"
line-length = 88

[tool.ruff.lint]
select = [
    "E",  # pycodestyle errors
    "W",  # pycodestyle warnings
    "F",  # pyflakes
    "I",  # isort
    "B",  # flake8-bugbear
    "C4", # flake8-comprehensions
    "UP", # pyupgrade
]
ignore = [
    "E501",  # line too long
    "B008",  # do not perform function calls in argument defaults
    "C901",  # too complex
]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]

[tool.ruff.lint.isort]
known-first-party = ["dotmac"]

[tool.mypy]
python_version = "3.9"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
