[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]

name = "dotmac-billing"
version = "1.0.0"
description = "Comprehensive billing system for ISP and service provider applications"
authors = ["DotMac Framework Team <support@dotmac.dev>"]
readme = "README.md"
license = "MIT"
homepage = "https://github.com/dotmac-framework/dotmac-billing"
repository = "https://github.com/dotmac-framework/dotmac-billing.git"
documentation = "https://docs.dotmac.com/billing"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Development Status :: 4 - Beta",
    "Topic :: Office/Business :: Financial :: Accounting",
    "Topic :: Internet :: WWW/HTTP :: Dynamic Content",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
packages = [{include = "dotmac", from = "src"}]

[tool.poetry.dependencies]

python = "^3.9"
sqlalchemy = ">=2.0.0"
pydantic = ">=2.5.0"
fastapi = ">=0.110.0"
alembic = ">=1.11.0"
python-dateutil = ">=2.8.0"


[tool.poetry.group.dev.dependencies]

pytest = ">=7.0.0"
pytest-asyncio = ">=0.21.0"
pytest-cov = ">=4.1.0"
black = ">=23.0.0"
flake8 = ">=6.0.0"
mypy = ">=1.5.0"
[tool.setuptools]



[tool.setuptools.packages]

[tool.setuptools.packages.find]

where = ["."]
include = ["dotmac_shared.billing*"]

[tool.setuptools.package-data]
dotmac_shared.billing = ["templates/*.html", "migrations/*.sql", "config/*.yaml"]

[tool.black]
line-length = 100
target-version = ["py39", "py310", "py311", "py312"]
include = "\.pyi?$"
extend-exclude = "/(
  \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | migrations
)/
"[tool.mypy]

python_version = "3.9"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true


[tool.pytest]

[tool.pytest.ini_options]

minversion = "7.0"
addopts = "-ra -q --cov=dotmac_shared.billing --cov-report=term-missing"
testpaths = ["tests"]
asyncio_mode = "auto"
