# DotMac Framework - Optimized Dependabot Configuration
# Reduced email spam, focuses on actual directories

version: 2
updates:
  # Root Python dependencies (main project)
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"  # Reduced from weekly
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "automerge-candidate"
    open-pull-requests-limit: 5  # Reduced from 10
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"

  # Core packages (consolidated)
  - package-ecosystem: "pip" 
    directory: "/packages"
    schedule:
      interval: "monthly"
      day: "monday"
    commit-message:
      prefix: "deps(packages)"
    labels:
      - "dependencies"
      - "packages"
    open-pull-requests-limit: 8

  # Frontend dependencies (pnpm)
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "monthly"
      day: "monday"
    commit-message:
      prefix: "deps(frontend)"
    labels:
      - "dependencies" 
      - "frontend"
    open-pull-requests-limit: 5

  # GitHub Actions (keep weekly for security)
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    commit-message:
      prefix: "ci"
    labels:
      - "github-actions"
      - "automerge-candidate"
    open-pull-requests-limit: 3

  # Docker (if Dockerfiles exist)
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "deps(docker)"
    labels:
      - "dependencies"
      - "docker"
    open-pull-requests-limit: 2

# Global settings to reduce noise
enable-beta-ecosystems: false