version: '3.8'

services:
  admin:
    build:
      context: .
      dockerfile: apps/admin/Dockerfile
    image: dotmac/admin-portal:latest
    container_name: dotmac-admin
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0
      - NEXT_PUBLIC_API_URL=${API_URL:-http://api:8000}
      - NEXT_PUBLIC_WEBSOCKET_URL=${WEBSOCKET_URL:-ws://api:3001}
      - NEXT_PUBLIC_APP_NAME=DotMac Admin Portal
      - NEXT_PUBLIC_APP_DESCRIPTION=ISP Administration Portal
      - NEXT_PUBLIC_OTEL_ENDPOINT=${OTEL_ENDPOINT:-}
      - NEXT_PUBLIC_SENTRY_DSN=${SENTRY_DSN:-}
      - SHUTDOWN_GRACE_PERIOD=30000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 40s
    networks:
      - dotmac-network
    depends_on:
      - api

  customer:
    build:
      context: .
      dockerfile: apps/customer/Dockerfile
    image: dotmac/customer-portal:latest
    container_name: dotmac-customer
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - HOSTNAME=0.0.0.0
      - NEXT_PUBLIC_API_URL=${API_URL:-http://api:8000}
      - NEXT_PUBLIC_WEBSOCKET_URL=${WEBSOCKET_URL:-ws://api:3001}
      - NEXT_PUBLIC_APP_NAME=DotMac Customer Portal
      - NEXT_PUBLIC_APP_DESCRIPTION=Customer Self-Service Portal
      - NEXT_PUBLIC_OTEL_ENDPOINT=${OTEL_ENDPOINT:-}
      - NEXT_PUBLIC_SENTRY_DSN=${SENTRY_DSN:-}
      - SHUTDOWN_GRACE_PERIOD=30000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 40s
    networks:
      - dotmac-network
    depends_on:
      - api

  reseller:
    build:
      context: .
      dockerfile: apps/reseller/Dockerfile
    image: dotmac/reseller-portal:latest
    container_name: dotmac-reseller
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
      - PORT=3002
      - HOSTNAME=0.0.0.0
      - NEXT_PUBLIC_API_URL=${API_URL:-http://api:8000}
      - NEXT_PUBLIC_WEBSOCKET_URL=${WEBSOCKET_URL:-ws://api:3001}
      - NEXT_PUBLIC_APP_NAME=DotMac Reseller Portal
      - NEXT_PUBLIC_APP_DESCRIPTION=Partner Portal
      - NEXT_PUBLIC_OTEL_ENDPOINT=${OTEL_ENDPOINT:-}
      - NEXT_PUBLIC_SENTRY_DSN=${SENTRY_DSN:-}
      - SHUTDOWN_GRACE_PERIOD=30000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3002/api/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 40s
    networks:
      - dotmac-network
    depends_on:
      - api

  # Nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: dotmac-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 5s
      retries: 3
    networks:
      - dotmac-network
    depends_on:
      - admin
      - customer
      - reseller

  # Mock API service for testing (replace with actual backend)
  api:
    image: mockserver/mockserver:latest
    container_name: dotmac-api
    ports:
      - "8000:1080"
    environment:
      - MOCKSERVER_PROPERTY_FILE=/config/mockserver.properties
      - MOCKSERVER_INITIALIZATION_JSON_PATH=/config/initializerJson.json
    volumes:
      - ./mock-api/config:/config:ro
    networks:
      - dotmac-network

networks:
  dotmac-network:
    driver: bridge
    name: dotmac-network

volumes:
  nginx-cache:
    driver: local