// Lighthouse CI configuration for reseller
// Generated by create-lighthouse-config.js - DO NOT EDIT MANUALLY
// To regenerate, run: node scripts/create-lighthouse-config.js

const baseConfig = require('../../lighthouse.base.js');

module.exports = {
  ...baseConfig,
  ci: {
    ...baseConfig.ci,
    collect: {
      ...baseConfig.ci.collect,
      url: [
        'http://localhost:3002/',
        'http://localhost:3002/dashboard',
        'http://localhost:3002/customers',
        'http://localhost:3002/commission',
        'http://localhost:3002/territory',
      ],
      startServerCommand: 'pnpm start',
      startServerReadyPattern: 'Ready on',
      startServerReadyTimeout: 60000,
    },
    server: {
      ...baseConfig.ci.server,
      port: 12002,
    },
  },
};
