repos:
- repo: local
  hooks:
  - id: syntax-validation
    name: Python Syntax Validation
    entry: python .dev-artifacts/scripts/syntax_validator.py
    language: system
    files: \.py$
    exclude: ^(templates/|tools/|docs/)
    pass_filenames: false
    args: [--fail-on-templates, "false"]
  
  - id: import-policy-check
    name: Import Policy Validation
    entry: python .dev-artifacts/scripts/import_policy_checker.py
    language: system
    files: \.py$
    exclude: ^(templates/|tools/|docs/)
    pass_filenames: false
    args: [--fail-on-errors]
  
  - id: python-ast
    name: Python AST Check
    entry: python -m py_compile
    language: system
    files: \.py$
    exclude: ^(templates/|tools/|docs/)
  
  - id: check-critical-module-exceptions
    name: Check critical modules for broad exceptions
    entry: python scripts/check_broad_exceptions.py
    language: system
    pass_filenames: false
    files: '^(src/dotmac_shared/repositories/|src/dotmac_management/core/).*\.py$'

- repo: https://github.com/psf/black
  rev: 23.3.0
  hooks:
  - id: black
    files: ^src/
    exclude: ^(templates/|tools/|docs/)

- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
  - id: isort
    files: ^src/
    exclude: ^(templates/|tools/|docs/)
    args: [--profile=black]

- repo: https://github.com/pycqa/flake8
  rev: 6.0.0
  hooks:
  - id: flake8
    files: ^src/
    exclude: ^(templates/|tools/|docs/)
    args: [--max-line-length=88, --extend-ignore=E203,W503]