# Coolify Docker Compose Configuration
# This file is specifically designed for Coolify deployment
# Uses SERVICE_TYPE pattern with a single image

version: '3.8'

services:
  # DB Migration Job (runs once, then exits)
  # Prevents multi-replica migration races
  db-migrate:
    image: ghcr.io/dotmac/dotmac-framework:latest
    restart: "no"  # Run once and exit
    environment:
      - SERVICE_TYPE=migration
      - DATABASE_URL=${DATABASE_URL}
      - PYTHONPATH=/app/src
    volumes:
      - migration_logs:/app/logs
    healthcheck:
      test: ["CMD", "test", "-f", "/app/migration_complete"]
      interval: 5s
      timeout: 3s
      retries: 12  # 1 minute max
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    command: ["/migrate.sh"]

  # ISP Service
  dotmac-isp:
    image: ghcr.io/dotmac/dotmac-framework:latest
    restart: unless-stopped
    environment:
      # Service Configuration
      - SERVICE_TYPE=isp
      
      # Database Connection (injected by Coolify)
      - DATABASE_URL=${DATABASE_URL}
      
      # Redis Connection (injected by Coolify)  
      - REDIS_URL=${REDIS_URL}
      
      # Application Settings
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=false
      - ENVIRONMENT=production
      - LOG_LEVEL=info
      
      # ISP-specific settings
      - ISP_API_VERSION=v1
      - MAX_UPLOAD_SIZE=100MB
      - RATE_LIMIT_PER_MINUTE=1000
      
    ports:
      - "8000:8000"
    
    volumes:
      - isp_logs:/app/logs
      - isp_uploads:/app/uploads
      - isp_temp:/app/temp
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 90s
    depends_on:
      db-migrate:
        condition: service_completed_successfully
    
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M

  # Management Service
  dotmac-management:
    image: ghcr.io/dotmac/dotmac-framework:latest
    restart: unless-stopped
    environment:
      # Service Configuration
      - SERVICE_TYPE=management
      
      # Database Connection (injected by Coolify)
      - DATABASE_URL=${DATABASE_URL}
      
      # Redis Connection (injected by Coolify)
      - REDIS_URL=${REDIS_URL}
      
      # Application Settings
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=false
      - ENVIRONMENT=production
      - LOG_LEVEL=info
      
      # Management-specific settings
      - MANAGEMENT_API_VERSION=v1
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - WEBHOOK_SECRET=${WEBHOOK_SECRET}
      
    ports:
      - "8001:8001"
    
    volumes:
      - management_logs:/app/logs
      - management_uploads:/app/uploads
      - management_temp:/app/temp
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 90s
    depends_on:
      db-migrate:
        condition: service_completed_successfully
    
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M

volumes:
  migration_logs:
  isp_logs:
  isp_uploads:
  isp_temp:
  management_logs:
  management_uploads:
  management_temp: