version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: dotmac-postgres
    environment:
      POSTGRES_USER: dotmac
      POSTGRES_PASSWORD: dotmac123
      POSTGRES_DB: dotmac
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dotmac"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: dotmac-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # FreeRADIUS
  freeradius:
    image: freeradius/freeradius-server:latest
    container_name: dotmac-freeradius
    ports:
      - "1812:1812/udp"
      - "1813:1813/udp"

volumes:
  postgres_data:
    name: dotmac-postgres-data