version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: isp_platform
      POSTGRES_USER: isp_user
      POSTGRES_PASSWORD: isp_secure_pass_123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U isp_user -d isp_platform"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

  isp_framework:
    build:
      context: .
      dockerfile: Dockerfile.isp
    environment:
      - ENVIRONMENT=production
      - DATABASE_URL=postgresql://isp_user:isp_secure_pass_123@postgres:5432/isp_platform
      - ASYNC_DATABASE_URL=postgresql+asyncpg://isp_user:isp_secure_pass_123@postgres:5432/isp_platform
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=production-secret-key-change-me-32-chars
      - JWT_SECRET_KEY=production-jwt-secret-change-me-32-chars
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - ./logs:/app/logs
    command: uvicorn dotmac_isp.app:app --host 0.0.0.0 --port 8000

volumes:
  postgres_data:
  redis_data:
