[tool.poetry]
name = "dotmac-framework"
version = "0.1.0"
description = "DotMac ISP Framework - Production-ready ISP management platform"
authors = ["DotMac Team <team@dotmac.io>"]
readme = "README.md"
packages = [{include = "dotmac_isp", from = "src"}, {include = "dotmac_management", from = "src"}, {include = "dotmac_shared", from = "src"}]

[tool.poetry.dependencies]
python = ">=3.9,<4.0"

# Core Framework Dependencies
fastapi = ">=0.100.0"
uvicorn = {extras = ["standard"], version = ">=0.23.0"}
pydantic = ">=2.0.0"
pydantic-settings = ">=2.0.0"
sqlalchemy = ">=2.0.0"
alembic = ">=1.11.0"
asyncpg = ">=0.28.0"
redis = ">=5.0.0"

# Authentication & Security
python-jose = {extras = ["cryptography"], version = ">=3.3.0"}
passlib = {extras = ["bcrypt"], version = ">=1.7.0"}
python-multipart = ">=0.0.6"
cryptography = ">=41.0.0"
pyotp = ">=2.9.0"
qrcode = {extras = ["pil"], version = ">=7.4.0"}
bcrypt = ">=4.0.0"

# HTTP & API Clients
httpx = ">=0.24.0"
aiohttp = ">=3.8.0"
requests = ">=2.31.0"
websockets = ">=11.0.0"
starlette = ">=0.27.0"

# Configuration & Environment
python-dotenv = ">=1.0.0"
click = ">=8.1.0"
typing-extensions = ">=4.7.0"

# Logging & Observability
structlog = ">=23.1.0"
opentelemetry-sdk = ">=1.20.0"
opentelemetry-exporter-otlp = ">=1.20.0"
opentelemetry-instrumentation-fastapi = ">=0.41b0"
opentelemetry-instrumentation-asgi = ">=0.41b0"
opentelemetry-instrumentation-logging = ">=0.41b0"
opentelemetry-instrumentation-requests = ">=0.41b0"
opentelemetry-instrumentation-httpx = ">=0.41b0"
opentelemetry-instrumentation-sqlalchemy = ">=0.41b0"
prometheus-client = ">=0.17.0"
psutil = ">=5.9.0"

# Core Processing Dependencies
jinja2 = ">=3.1.0"
email-validator = ">=2.0.0"
tenacity = ">=8.0.0"

# Cloud & Infrastructure  
boto3 = ">=1.28.0"
botocore = ">=1.31.0"
docker = ">=6.1.0"

# Networking
dnspython = ">=2.4.0"
paramiko = ">=3.3.0"

# Task Processing
celery = ">=5.3.0"
dramatiq = {extras = ["redis"], version = ">=1.13.0"}
pika = ">=1.3.0"

# File Handling
aiofiles = ">=23.2.0"

# Data Validation
jsonschema = ">=4.19.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"