line-length = 120
target-version = "py311"

[lint]
select = [
  "E",  # pycodestyle errors
  "F",  # pyflakes
  "I",  # isort
]
ignore = []

[format]
quote-style = "preserve"
indent-style = "space"
skip-magic-trailing-comma = false

