[build-system]
requires = ["poetry-core"]

build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "dotmac-shared-core"
version = "1.0.0"
description = "Foundational utilities for the DotMac framework"
authors = ["DotMac Framework Team <dev@dotmac.com>"]

readme = "README.md"
license = "MIT"
homepage = "https://github.com/dotmac-framework/dotmac-shared-core"
repository = "https://github.com/dotmac-framework/dotmac-shared-core.git"
documentation = "https://docs.dotmac.com/shared-core"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Utilities"
]

# Ensure src layout packaging
packages = [
    { include = "dotmac_shared_core", from = "src" }
]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.group.dev.dependencies]
pytest = ">=7.0.0"
pytest-cov = ">=4.0.0"
mypy = ">=1.0.0"
ruff = ">=0.1.0"

[tool.pytest]
[tool.pytest.ini_options]
testpaths = ["tests"]

python_files = ["test_*.py", "*_test.py"]

python_functions = ["test_*"]

addopts = [
    "-v",
    "--tb=short",
    "--strict-markers",
    "--strict-config",
    "--cov=dotmac_shared_core",
    "--cov-report=term-missing",
    "--cov-report=html",
    "--cov-report=xml",
    "--cov-fail-under=95"
]

markers = [
    "unit: marks tests as unit tests",
    "property: marks tests as property-based tests"
]

asyncio_mode = "auto"

[tool.coverage]

[tool.coverage.run]
source = ["src/dotmac_shared_core"]

omit = ["*/tests/*", "*/test_*", "*/__init__.py"]

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "def __repr__",
    "raise AssertionError",
    "raise NotImplementedError",
    "if __name__ == \"__main__\":",
    "if TYPE_CHECKING:"
]

[tool.mypy]
python_version = "3.9"
strict = true
warn_return_any = true
warn_unused_configs = true

[tool.ruff]
line-length = 100
target-version = "py39"

[tool.ruff.lint]

select = ["E", "W", "F", "I", "B", "C4", "UP", "S"]

ignore = ["E501"]

[tool.ruff.lint.per-file-ignores]
"tests/*" = ["S101"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"
