---
# SecretProviderClass for OpenBao integration with Kubernetes
# Allows pods to mount secrets from OpenBao as volumes
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: openbao-dotmac-identity
  namespace: dotmac
spec:
  provider: vault
  parameters:
    # OpenBao server address
    vaultAddress: "http://openbao.dotmac.svc.cluster.local:8200"

    # Authentication method
    roleName: "identity"
    vaultAuthMountPath: "kubernetes"

    # Secrets to mount
    objects: |
      - objectName: "jwt-secret"
        secretPath: "dotmac/data/jwt"
        secretKey: "secret_key"
      - objectName: "service-key"
        secretPath: "dotmac/data/identity"
        secretKey: "service_key"
      - objectName: "api-key"
        secretPath: "dotmac/data/identity"
        secretKey: "api_key"
      - objectName: "encryption-key"
        secretPath: "dotmac/data/identity"
        secretKey: "encryption_key"
      - objectName: "redis-password"
        secretPath: "dotmac/data/redis"
        secretKey: "password"
      - objectName: "signoz-endpoint"
        secretPath: "dotmac/data/observability"
        secretKey: "signoz_endpoint"
      - objectName: "signoz-token"
        secretPath: "dotmac/data/observability"
        secretKey: "signoz_access_token"

  # Create Kubernetes secrets from OpenBao secrets
  secretObjects:
    - secretName: dotmac-identity-secrets
      type: Opaque
      data:
        - objectName: jwt-secret
          key: JWT_SECRET_KEY
        - objectName: service-key
          key: SECRET_KEY
        - objectName: api-key
          key: API_KEY
        - objectName: encryption-key
          key: ENCRYPTION_KEY
        - objectName: redis-password
          key: REDIS_PASSWORD
        - objectName: signoz-endpoint
          key: SIGNOZ_ENDPOINT
        - objectName: signoz-token
          key: SIGNOZ_ACCESS_TOKEN

---
# SecretProviderClass for Billing service
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: openbao-dotmac-billing
  namespace: dotmac
spec:
  provider: vault
  parameters:
    vaultAddress: "http://openbao.dotmac.svc.cluster.local:8200"
    roleName: "billing"
    vaultAuthMountPath: "kubernetes"

    objects: |
      - objectName: "jwt-secret"
        secretPath: "dotmac/data/jwt"
        secretKey: "secret_key"
      - objectName: "service-key"
        secretPath: "dotmac/data/billing"
        secretKey: "service_key"
      - objectName: "stripe-secret"
        secretPath: "dotmac/data/external"
        secretKey: "stripe_secret_key"
      - objectName: "stripe-webhook"
        secretPath: "dotmac/data/billing"
        secretKey: "stripe_webhook_secret"

  secretObjects:
    - secretName: dotmac-billing-secrets
      type: Opaque
      data:
        - objectName: jwt-secret
          key: JWT_SECRET_KEY
        - objectName: service-key
          key: SECRET_KEY
        - objectName: stripe-secret
          key: STRIPE_SECRET_KEY
        - objectName: stripe-webhook
          key: STRIPE_WEBHOOK_SECRET

---
# SecretProviderClass for Core Events service
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: openbao-dotmac-core-events
  namespace: dotmac
spec:
  provider: vault
  parameters:
    vaultAddress: "http://openbao.dotmac.svc.cluster.local:8200"
    roleName: "core_events"
    vaultAuthMountPath: "kubernetes"

    objects: |
      - objectName: "jwt-secret"
        secretPath: "dotmac/data/jwt"
        secretKey: "secret_key"
      - objectName: "service-key"
        secretPath: "dotmac/data/core_events"
        secretKey: "service_key"
      - objectName: "redis-password"
        secretPath: "dotmac/data/redis"
        secretKey: "password"

  secretObjects:
    - secretName: dotmac-core-events-secrets
      type: Opaque
      data:
        - objectName: jwt-secret
          key: JWT_SECRET_KEY
        - objectName: service-key
          key: SECRET_KEY
        - objectName: redis-password
          key: REDIS_PASSWORD

---
# SecretProviderClass for API Gateway
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: openbao-dotmac-api-gateway
  namespace: dotmac
spec:
  provider: vault
  parameters:
    vaultAddress: "http://openbao.dotmac.svc.cluster.local:8200"
    roleName: "api_gateway"
    vaultAuthMountPath: "kubernetes"

    objects: |
      - objectName: "jwt-secret"
        secretPath: "dotmac/data/jwt"
        secretKey: "secret_key"
      - objectName: "service-key"
        secretPath: "dotmac/data/api_gateway"
        secretKey: "service_key"
      - objectName: "rate-limit-key"
        secretPath: "dotmac/data/api_gateway"
        secretKey: "rate_limit_key"

  secretObjects:
    - secretName: dotmac-api-gateway-secrets
      type: Opaque
      data:
        - objectName: jwt-secret
          key: JWT_SECRET_KEY
        - objectName: service-key
          key: SECRET_KEY
        - objectName: rate-limit-key
          key: RATE_LIMIT_KEY
