[build-system]
requires = ["setuptools>=64", "setuptools-scm>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "dotmac-secrets"
version = "1.0.0"
description = "Standalone secrets management package for DotMac Framework"
readme = "README.md"
requires-python = ">=3.10"
license = {text = "MIT"}
authors = [
    {name = "DotMac Framework", email = "dev@dotmac.framework"},
]
keywords = ["secrets", "vault", "openbao", "security", "credentials"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Security",
    "Topic :: Software Development :: Libraries :: Python Modules",
]

dependencies = [
    "typing_extensions>=4.0.0",
    "httpx>=0.27.0",
    "cryptography>=41.0.0",
    "pydantic>=2.0.0",
]

[project.optional-dependencies]
redis = ["redis>=5.0.0"]
otel = ["opentelemetry-api>=1.25.0"]
dev = [
    "pytest>=7.0.0",
    "pytest-asyncio>=0.23.0",
    "pytest-cov>=4.0.0",
    "pytest-mock>=3.11.0",
    "httpx-mock>=0.10.0",
    "mypy>=1.5.0",
    "ruff>=0.1.0",
]

[project.urls]
Homepage = "https://github.com/dotmac-framework/dotmac-secrets"
Documentation = "https://docs.dotmac.framework/secrets"
Repository = "https://github.com/dotmac-framework/dotmac-secrets"
"Bug Tracker" = "https://github.com/dotmac-framework/dotmac-secrets/issues"

[tool.setuptools.packages.find]
where = ["src"]
include = ["dotmac*"]

[tool.setuptools.package-data]
dotmac = ["py.typed"]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"
python_classes = "Test*"
python_functions = "test_*"
addopts = [
    "--strict-markers",
    "--strict-config",
    "--cov=dotmac.secrets",
    "--cov-report=term-missing",
    "--cov-report=html:htmlcov",
    "--cov-fail-under=85",
]
asyncio_mode = "auto"
markers = [
    "unit: Unit tests",
    "integration: Integration tests",
    "requires_openbao: Tests requiring OpenBao/Vault server",
    "requires_redis: Tests requiring Redis server",
]

[tool.mypy]
python_version = "3.10"
packages = ["dotmac.secrets"]
strict = true
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = true
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_no_return = true
warn_unreachable = true

[tool.ruff]
target-version = "py310"
line-length = 100
select = ["E", "F", "W", "I", "N", "UP", "B", "A", "C4", "PL"]
ignore = ["E501", "PLR0913", "PLR0912", "PLR0915"]

[tool.ruff.per-file-ignores]
"tests/*" = ["PLR2004", "S101", "S106"]

[tool.coverage.run]
source = ["dotmac.secrets"]
omit = [
    "*/tests/*",
    "*/test_*",
]

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "def __repr__",
    "if TYPE_CHECKING:",
    "raise AssertionError",
    "raise NotImplementedError",
    "@abstractmethod",
]