[build-system]
requires = ["poetry-core"]

build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "dotmac-service-kernel"
version = "1.0.0"
description = "Service and repository kernel for DotMac applications"
authors = ["DotMac Team <dev@dotmac.io>"]

readme = "README.md"
license = "MIT"
packages = [{include = "dotmac_service_kernel", from = "src"}]

[tool.poetry.dependencies]
python = "^3.9"
pydantic = ">=2.5.0"
typing-extensions = {version = "^4.0", python = "<3.10"}

[tool.poetry.group.dev.dependencies]
pytest = "^7.4"
pytest-asyncio = "^0.20"
pytest-cov = "^4.1"
mypy = "^1.5"

[tool.ruff]
target-version = "py39"
line-length = "100"

[tool.ruff.lint]
select = ["E", "W", "F", "I", "N", "UP", "S", "B", "A", "C4", "DTZ", "T20", "SIM", "ARG"]

ignore = ["S101", "S104", "B008", "B904"]

[tool.ruff.lint.per-file-ignores]
"tests/**" = ["S101", "ARG001", "ARG002"]

[tool.mypy]
python_version = "3.9"
strict = true
warn_return_any = true
warn_unused_configs = true

[tool.pytest]
[tool.pytest.ini_options]
minversion = "7.0"
addopts = "-ra -q --strict-markers"
testpaths = ["tests"]

asyncio_mode = "auto"
markers = ["unit: Unit tests", "integration: Integration tests"]

[tool.coverage]
[tool.coverage.run]
source = ["src"]

branch = true

[tool.coverage.report]
exclude_lines = ["pragma: no cover", "def __repr__", "raise AssertionError", "raise NotImplementedError", "if TYPE_CHECKING:"]
