# Alertmanager configuration for DotMac Framework
global:
  # SMTP configuration (optional - configure if using email alerts)
  smtp_smarthost: '${SMTP_SMARTHOST:-localhost:587}'
  smtp_from: '${SMTP_FROM:-alerts@your-domain.com}'
  smtp_auth_username: '${SMTP_AUTH_USERNAME:-}'
  smtp_auth_password: '${SMTP_AUTH_PASSWORD:-}'
  
  # Additional global configurations (all optional)
  slack_api_url: '${SLACK_API_URL:-}'
  victorops_api_url: '${VICTOROPS_API_URL:-}'
  pagerduty_url: '${PAGERDUTY_URL:-}'
  opsgenie_api_url: '${OPSGENIE_API_URL:-}'
  wechat_api_url: '${WECHAT_API_URL:-}'
  telegram_api_url: '${TELEGRAM_API_URL:-}'

# Templates for alert formatting
templates:
  - '/etc/alertmanager/templates/*.tmpl'

# Route configuration
route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'default'
  routes:
    # Critical alerts go to multiple channels
    - match:
        severity: critical
      receiver: 'critical-alerts'
      group_wait: 5s
      repeat_interval: 5m
      continue: true
    
    # Database alerts
    - match:
        service: database
      receiver: 'database-team'
      continue: true
    
    # Security alerts
    - match_re:
        alertname: 'AuthenticationFailures|SSL.*|Security.*'
      receiver: 'security-team'
      continue: true
    
    # ISP network infrastructure
    - match:
        service: network-infrastructure
      receiver: 'network-operations'
      continue: true
    
    # Tenant-specific alerts
    - match:
        service: tenant-management
      receiver: 'tenant-management-team'
      continue: true
    
    # Development/testing alerts (lower priority)
    - match:
        environment: development
      receiver: 'dev-alerts'
      repeat_interval: 6h

# Receivers configuration
receivers:
  # Default receiver
  - name: 'default'
    slack_configs:
      - channel: '#dotmac-alerts'
        username: 'DotMac Alerts'
        color: 'warning'
        title: 'DotMac Alert - {{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'
        text: '{{ range .Alerts }}{{ .Annotations.description }}{{ end }}'
        fields:
          - title: 'Service'
            value: '{{ .CommonLabels.service }}'
            short: true
          - title: 'Environment'
            value: '{{ .CommonLabels.environment }}'
            short: true
          - title: 'Runbook'
            value: '{{ range .Alerts }}{{ .Annotations.runbook_url }}{{ end }}'
            short: false

  # Critical alerts (multiple channels)
  - name: 'critical-alerts'
    slack_configs:
      - channel: '#dotmac-critical'
        username: 'DotMac CRITICAL'
        color: 'danger'
        title: '🚨 CRITICAL: {{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'
        text: '{{ range .Alerts }}{{ .Annotations.description }}{{ end }}'
        fields:
          - title: 'Service'
            value: '{{ .CommonLabels.service }}'
            short: true
          - title: 'Instance'
            value: '{{ .CommonLabels.instance }}'
            short: true
          - title: 'Runbook'
            value: '{{ range .Alerts }}{{ .Annotations.runbook_url }}{{ end }}'
            short: false
    email_configs:
      - to: 'oncall@dotmac.app'
        subject: '🚨 DotMac CRITICAL Alert: {{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'
        body: |
          Alert Details:
          {{ range .Alerts }}
          Summary: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Service: {{ .Labels.service }}
          Instance: {{ .Labels.instance }}
          Runbook: {{ .Annotations.runbook_url }}
          {{ end }}
    webhook_configs:
      - url: '${PAGERDUTY_WEBHOOK_URL}'
        send_resolved: true

  # Database team alerts
  - name: 'database-team'
    slack_configs:
      - channel: '#database-alerts'
        username: 'Database Monitor'
        color: 'warning'
        title: '🗄️ Database Alert: {{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'
        text: '{{ range .Alerts }}{{ .Annotations.description }}{{ end }}'
    email_configs:
      - to: 'database-team@dotmac.app'
        subject: 'Database Alert: {{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'

  # Security team alerts
  - name: 'security-team'
    slack_configs:
      - channel: '#security-alerts'
        username: 'Security Monitor'
        color: 'danger'
        title: '🔒 Security Alert: {{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'
        text: '{{ range .Alerts }}{{ .Annotations.description }}{{ end }}'
    email_configs:
      - to: 'security-team@dotmac.app'
        subject: '🔒 Security Alert: {{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'

  # Network operations team (ISP-specific)
  - name: 'network-operations'
    slack_configs:
      - channel: '#network-ops'
        username: 'Network Monitor'
        color: 'warning'
        title: '🌐 Network Alert: {{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'
        text: '{{ range .Alerts }}{{ .Annotations.description }}{{ end }}'
        fields:
          - title: 'Device'
            value: '{{ .CommonLabels.instance }}'
            short: true
          - title: 'Location'
            value: '{{ .CommonLabels.location }}'
            short: true
    email_configs:
      - to: 'network-ops@dotmac.app'
        subject: '🌐 Network Alert: {{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'

  # Tenant management team
  - name: 'tenant-management-team'
    slack_configs:
      - channel: '#tenant-management'
        username: 'Tenant Monitor'
        color: 'warning'
        title: '🏢 Tenant Alert: {{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'
        text: '{{ range .Alerts }}{{ .Annotations.description }}{{ end }}'
        fields:
          - title: 'Tenant ID'
            value: '{{ .CommonLabels.tenant_id }}'
            short: true
          - title: 'Resource Type'
            value: '{{ .CommonLabels.resource_type }}'
            short: true

  # Development alerts (lower priority)
  - name: 'dev-alerts'
    slack_configs:
      - channel: '#dev-alerts'
        username: 'Dev Monitor'
        color: 'good'
        title: '🔧 Dev Alert: {{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'
        text: '{{ range .Alerts }}{{ .Annotations.description }}{{ end }}'

# Inhibit rules
inhibit_rules:
  # Inhibit any warning-level alerts if there are critical alerts for the same service
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['service', 'instance']
  
  # Inhibit high error rate alerts if service is down
  - source_match:
      alertname: 'ServiceDown'
    target_match_re:
      alertname: 'HighErrorRate|HighResponseTime'
    equal: ['service']

  # Inhibit database connection alerts if database is down
  - source_match:
      alertname: 'PostgreSQLDown'
    target_match:
      alertname: 'DatabaseConnectionFailure'
    equal: ['instance']