[build-system]
requires = ["poetry-core"]

build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "dotmac-communications"
version = "1.0.0"
description = "DotMac comprehensive communication system - notifications, websockets, and events"
authors = ["DotMac Framework Team <dev@dotmac.framework>"]

readme = "README.md"
license = "MIT"
packages = [{include = "dotmac", from = "src"}]

[tool.poetry.dependencies]
python = "^3.9"
dotmac-core = {path = "../dotmac-core", develop = true}
dotmac-platform-services = {path = "../dotmac-platform-services", develop = true, optional = true}
pydantic = ">=2.5.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.0.0"
pytest-asyncio = "^0.21.0"
pytest-mock = "^3.10.0"
black = "^23.0.0"

[tool.black]
line-length = "100"
target-version = ["py39", "py310", "py311", "py312"]

[tool.isort]
profile = "black"
line_length = "100"

[tool.ruff]
target-version = "py39"
line-length = "100"

[tool.ruff.lint]
select = ["E", "F", "I", "N", "W", "UP"]

ignore = ["E501", "N805"]

[tool.mypy]
python_version = "3.9"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true

[tool.pytest]
[tool.pytest.ini_options]
minversion = "7.0"
addopts = [
    "--strict-markers",
    "--strict-config", 
    "--cov=dotmac.communications",
    "--cov-report=term-missing"
]

testpaths = ["tests"]

python_files = ["test_*.py"]

python_classes = ["Test*"]

python_functions = ["test_*"]

markers = ["integration: marks tests as integration tests", "unit: marks tests as unit tests", "redis: marks tests that require Redis", "async: marks tests as async tests"]

asyncio_mode = "auto"
