[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "dotmac-communications"
version = "1.0.0"
description = "DotMac comprehensive communication system - notifications, websockets, and events"
authors = ["DotMac Framework Team <dev@dotmac.framework>"]
readme = "README.md"
license = "MIT"
packages = [{include = "dotmac", from = "src"}]

[tool.poetry.dependencies]
python = ">=3.9,<4.0"
# Core foundation
dotmac-core = {path = "../dotmac-core", develop = true}
dotmac-platform-services = {path = "../dotmac-platform-services", develop = true, optional = true}
pydantic = "^2.0.0"
fastapi = ">=0.100.0"
sqlalchemy = "^2.0.0"
redis = "^5.0.0"
httpx = "^0.25.0"
aioredis = "^2.0.1"
jinja2 = "^3.1.2"
structlog = "^23.0.0"
cryptography = "^41.0.0"
email-validator = "^2.1.0"
websockets = "^11.0.0"
uvicorn = {extras = ["standard"], version = ">=0.20.0"}
typing-extensions = "^4.0.0"

# Optional dependencies
celery = {version = "^5.2.0", optional = true}
pywebpush = {version = "^1.14.0", optional = true}
twilio = {version = "^8.0.0", optional = true}

[tool.poetry.extras]
celery = ["celery"]
push = ["pywebpush"]
sms = ["twilio"]
platform = ["dotmac-platform-services"]
all = ["celery", "pywebpush", "twilio", "dotmac-platform-services"]

[tool.poetry.group.dev.dependencies]
pytest = "^7.0.0"
pytest-asyncio = "^0.21.0"
pytest-mock = "^3.10.0"
black = "^23.0.0"
isort = "^5.12.0"
ruff = "^0.1.0"
mypy = "^1.0.0"

# Black configuration
[tool.black]
line-length = 100
target-version = ['py39', 'py310', 'py311', 'py312']

# isort configuration  
[tool.isort]
profile = "black"
line_length = 100

# Ruff configuration
[tool.ruff]
target-version = "py39"
line-length = 100

[tool.ruff.lint]
select = ["E", "F", "I", "N", "W", "UP"]
ignore = ["E501"]

# MyPy configuration
[tool.mypy]
python_version = "3.9"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = true
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_no_return = true
warn_unreachable = true
strict_equality = true

[[tool.mypy.overrides]]
module = [
    "redis.*",
    "celery.*", 
    "twilio.*",
    "pywebpush.*",
    "websockets.*",
]
ignore_missing_imports = true

# Pytest configuration
[tool.pytest.ini_options]
minversion = "7.0"
addopts = [
    "--strict-markers",
    "--strict-config", 
    "--cov=dotmac.communications",
    "--cov-report=term-missing",
]
testpaths = ["tests"]
python_files = ["test_*.py"]
python_classes = ["Test*"] 
python_functions = ["test_*"]
markers = [
    "integration: marks tests as integration tests",
    "unit: marks tests as unit tests",
    "redis: marks tests that require Redis",
    "async: marks tests as async tests",
]