[tool.poetry]
name = "dotmac-network-automation"
version = "0.1.0"
description = "Network automation toolkit with RADIUS management, VOLTHA integration, and SSH device provisioning"
authors = ["DotMac Framework Team"]
readme = "README.md"
packages = [{include = "dotmac_network"}]

[tool.poetry.dependencies]
python = "^3.11"
# Core networking dependencies
paramiko = "^3.4.0"
netmiko = "^4.3.0"
scapy = "^2.5.0"
pysnmp = "^7.1.21"

# RADIUS and authentication
pyrad = "^2.4"
ldap3 = "^2.9.1"

# gRPC and protobuf for VOLTHA
grpcio = "^1.60.0"
grpcio-tools = "^1.60.0"
protobuf = "^4.25.0"

# HTTP clients and APIs
httpx = "^0.26.0"
aiohttp = "^3.9.1"

# Data processing and validation
pydantic = "^2.5.0"
pyyaml = "^6.0"
jinja2 = "^3.1.3"

# Async support
asyncio-mqtt = "^0.16.0"
aiofiles = "^23.2.0"

# Utilities
structlog = "^25.4.0"
tenacity = "^8.2.3"
click = "^8.1.7"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.0"
pytest-asyncio = "^0.21.0"
pytest-cov = "^4.1.0"
pytest-mock = "^3.12.0"
black = "^23.12.0"
isort = "^5.13.0"
mypy = "^1.8.0"
ruff = "^0.1.0"
faker = "^20.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 100
target-version = ['py311']

[tool.isort]
profile = "black"
line_length = 100

[tool.mypy]
python_version = "3.11"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true

[tool.ruff]
select = ["E", "F", "W", "C90", "I", "N", "UP", "YTT", "S", "B", "A", "COM", "DTZ", "EM", "ISC", "ICN", "G", "PIE", "T20", "PYI", "PT", "Q", "RSE", "RET", "SLF", "SIM", "TID", "TCH", "ARG", "PTH", "ERA", "PD", "PGH", "PL", "TRY", "NPY", "RUF"]
ignore = ["E501", "COM812", "ISC001", "PLR2004", "TRY003"]
line-length = 100
target-version = "py311"

[tool.pytest.ini_options]
asyncio_mode = "auto"
testpaths = ["tests"]
python_files = "test_*.py"
python_functions = "test_*"
addopts = "--cov=dotmac_network --cov-report=term-missing --cov-report=html"
