[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "dotmac-ticketing"
version = "1.0.0"
description = "Comprehensive ticketing system for DotMac Framework"
authors = ["DotMac Framework Team <dev@dotmac.com>"]
readme = "README.md"
license = "MIT"
homepage = "https://github.com/dotmac-framework/dotmac-ticketing"
repository = "https://github.com/dotmac-framework/dotmac-ticketing.git"
documentation = "https://docs.dotmac.com/ticketing"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12"
]
packages = [
    { include = "dotmac", from = "src" }
]

[tool.poetry.dependencies]
python = "^3.9"
pydantic = ">=2.5.0"
sqlalchemy = ">=2.0.0"
fastapi = ">=0.110.0"
python-multipart = ">=0.0.6"
structlog = ">=23.0.0"
pyotp = ">=2.9.0"

[tool.poetry.group.dev.dependencies]
pytest = ">=7.0.0"
pytest-cov = ">=4.0.0"
ruff = ">=0.1.0"

[tool.ruff]
line-length = 100
target-version = "py39"

[tool.ruff.lint]
select = ["E", "F", "W", "C", "I", "N", "B"]
ignore = ["E203", "C901"]

[tool.ruff.lint.isort]
known-first-party = ["dotmac"]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py", "*_test.py"]
addopts = ["--strict-markers", "--strict-config", "--disable-warnings"]
asyncio_mode = "auto"

[tool.coverage.run]
source = ["src"]
branch = true

[tool.coverage.report]
show_missing = true
exclude_lines = ["pragma: no cover", "def __repr__", "raise AssertionError", "raise NotImplementedError"]
