[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "dotmac-ticketing"
version = "1.0.0"
description = "Comprehensive ticketing system for DotMac Framework"
readme = "README.md"
requires-python = ">=3.11"
authors = [
    {name = "DotMac Framework Team", email = "dev@dotmac.com"}
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]
dependencies = [
    "pydantic>=2.0.0",
    "sqlalchemy>=2.0.0",
    "fastapi>=0.104.0",
    "python-multipart>=0.0.6",
    "structlog>=23.0.0",
    "pyotp>=2.9.0",
]

[project.optional-dependencies]
enterprise = [
    "redis>=5.0.0",
    "celery>=5.3.0",
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"*" = ["py.typed"]

[tool.ruff]
line-length = 88
target-version = "py311"
select = ["E", "F", "W", "C", "I", "N", "B"]
ignore = ["E203", "C901"]

[tool.ruff.isort]
known-first-party = ["dotmac"]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py", "*_test.py"]
addopts = [
    "--strict-markers",
    "--strict-config",
    "--disable-warnings",
]

[tool.coverage.run]
source = ["src"]
branch = true

[tool.coverage.report]
show_missing = true
exclude_lines = [
    "pragma: no cover",
    "def __repr__",
    "raise AssertionError",
    "raise NotImplementedError",
]