"""add_management_and_vps_tables

Revision ID: 90ab336e04eb
Revises: 0001_initial_baseline
Create Date: 2025-09-01 13:44:35.718945

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import Text
from dotmac_shared.database.mixins import GUID

# revision identifiers, used by Alembic.
revision = '90ab336e04eb'
down_revision = '0001_initial_baseline'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_tenants',
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('subdomain', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('plan', sa.String(length=50), nullable=False),
    sa.Column('region', sa.String(length=50), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('admin_email', sa.String(length=255), nullable=False),
    sa.Column('admin_name', sa.String(length=200), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('container_id', sa.String(length=100), nullable=True),
    sa.Column('database_url', sa.String(length=500), nullable=True),
    sa.Column('redis_url', sa.String(length=500), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('environment_vars', sa.JSON(), nullable=True),
    sa.Column('provisioning_logs', sa.JSON(), nullable=True),
    sa.Column('provisioning_started_at', sa.DateTime(), nullable=True),
    sa.Column('provisioning_completed_at', sa.DateTime(), nullable=True),
    sa.Column('last_health_check', sa.DateTime(), nullable=True),
    sa.Column('health_status', sa.String(length=50), nullable=True),
    sa.Column('billing_email', sa.String(length=255), nullable=True),
    sa.Column('payment_method_id', sa.String(length=100), nullable=True),
    sa.Column('subscription_id', sa.String(length=100), nullable=True),
    sa.Column('next_billing_date', sa.DateTime(), nullable=True),
    sa.Column('enabled_features', sa.JSON(), nullable=True),
    sa.Column('feature_limits', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', GUID(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_tenants_status'), 'customer_tenants', ['status'], unique=False)
    op.create_index(op.f('ix_customer_tenants_subdomain'), 'customer_tenants', ['subdomain'], unique=True)
    op.create_index(op.f('ix_customer_tenants_tenant_id'), 'customer_tenants', ['tenant_id'], unique=True)
    op.create_table('infrastructure_templates',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('cloud_provider', sa.Enum('AWS', 'AZURE', 'GCP', 'DIGITALOCEAN', 'KUBERNETES', name='cloudprovider'), nullable=False),
    sa.Column('resource_tier', sa.Enum('MICRO', 'SMALL', 'MEDIUM', 'LARGE', 'XLARGE', name='resourcetier'), nullable=False),
    sa.Column('cpu_cores', sa.Integer(), nullable=False),
    sa.Column('memory_gb', sa.Integer(), nullable=False),
    sa.Column('storage_gb', sa.Integer(), nullable=False),
    sa.Column('network_bandwidth_mbps', sa.Integer(), nullable=False),
    sa.Column('hourly_cost_cents', sa.Integer(), nullable=False),
    sa.Column('monthly_cost_cents', sa.Integer(), nullable=False),
    sa.Column('template_config', postgresql.JSON(astext_type=Text()), nullable=False),
    sa.Column('environment_variables', postgresql.JSON(astext_type=Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_infrastructure_templates_cloud_provider'), 'infrastructure_templates', ['cloud_provider'], unique=False)
    op.create_index(op.f('ix_infrastructure_templates_id'), 'infrastructure_templates', ['id'], unique=False)
    op.create_index(op.f('ix_infrastructure_templates_is_active'), 'infrastructure_templates', ['is_active'], unique=False)
    op.create_index(op.f('ix_infrastructure_templates_is_deleted'), 'infrastructure_templates', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_infrastructure_templates_name'), 'infrastructure_templates', ['name'], unique=False)
    op.create_index(op.f('ix_infrastructure_templates_resource_tier'), 'infrastructure_templates', ['resource_tier'], unique=False)
    op.create_table('plugin_categories',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=255), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plugin_categories_id'), 'plugin_categories', ['id'], unique=False)
    op.create_index(op.f('ix_plugin_categories_is_active'), 'plugin_categories', ['is_active'], unique=False)
    op.create_index(op.f('ix_plugin_categories_is_deleted'), 'plugin_categories', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_plugin_categories_name'), 'plugin_categories', ['name'], unique=False)
    op.create_index(op.f('ix_plugin_categories_slug'), 'plugin_categories', ['slug'], unique=True)
    op.create_table('pricing_plans',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('plan_type', sa.Enum('FIXED', 'USAGE_BASED', 'TIERED', 'HYBRID', name='pricingplantype'), nullable=False),
    sa.Column('base_price_cents', sa.Integer(), nullable=False),
    sa.Column('setup_fee_cents', sa.Integer(), nullable=False),
    sa.Column('billing_interval', sa.String(length=20), nullable=False),
    sa.Column('billing_interval_count', sa.Integer(), nullable=False),
    sa.Column('trial_days', sa.Integer(), nullable=False),
    sa.Column('max_tenants', sa.Integer(), nullable=False),
    sa.Column('max_users', sa.Integer(), nullable=False),
    sa.Column('max_storage_gb', sa.Integer(), nullable=False),
    sa.Column('max_bandwidth_gb', sa.Integer(), nullable=False),
    sa.Column('max_api_calls', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('features', postgresql.JSON(astext_type=Text()), nullable=False),
    sa.Column('usage_limits', postgresql.JSON(astext_type=Text()), nullable=False),
    sa.Column('pricing_tiers', postgresql.JSON(astext_type=Text()), nullable=False),
    sa.Column('stripe_price_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_product_id', sa.String(length=255), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pricing_plans_id'), 'pricing_plans', ['id'], unique=False)
    op.create_index(op.f('ix_pricing_plans_is_active'), 'pricing_plans', ['is_active'], unique=False)
    op.create_index(op.f('ix_pricing_plans_is_deleted'), 'pricing_plans', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_pricing_plans_name'), 'pricing_plans', ['name'], unique=False)
    op.create_index(op.f('ix_pricing_plans_plan_type'), 'pricing_plans', ['plan_type'], unique=False)
    op.create_index(op.f('ix_pricing_plans_slug'), 'pricing_plans', ['slug'], unique=True)
    op.create_index(op.f('ix_pricing_plans_stripe_price_id'), 'pricing_plans', ['stripe_price_id'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('tenant_id', GUID(), nullable=True),
    sa.Column('permissions', sa.Text(), nullable=True),
    sa.Column('password_changed_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('login_count', sa.Integer(), nullable=False),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('two_factor_enabled', sa.Boolean(), nullable=False),
    sa.Column('two_factor_secret', sa.String(length=32), nullable=True),
    sa.Column('email_notifications', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['customer_tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_is_deleted'), 'users', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_table('deployments',
    sa.Column('tenant_id', GUID(), nullable=False),
    sa.Column('infrastructure_template_id', GUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROVISIONING', 'DEPLOYING', 'RUNNING', 'UPDATING', 'STOPPING', 'STOPPED', 'FAILED', 'DELETING', 'DELETED', name='deploymentstatus'), nullable=False),
    sa.Column('cloud_provider', sa.Enum('AWS', 'AZURE', 'GCP', 'DIGITALOCEAN', 'KUBERNETES', name='cloudprovider'), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=False),
    sa.Column('availability_zone', sa.String(length=100), nullable=True),
    sa.Column('resource_tier', sa.Enum('MICRO', 'SMALL', 'MEDIUM', 'LARGE', 'XLARGE', name='resourcetier'), nullable=False),
    sa.Column('allocated_cpu', sa.Integer(), nullable=False),
    sa.Column('allocated_memory_gb', sa.Integer(), nullable=False),
    sa.Column('allocated_storage_gb', sa.Integer(), nullable=False),
    sa.Column('public_ip', sa.String(length=45), nullable=True),
    sa.Column('private_ip', sa.String(length=45), nullable=True),
    sa.Column('domain_name', sa.String(length=255), nullable=True),
    sa.Column('ssl_enabled', sa.Boolean(), nullable=False),
    sa.Column('dotmac_version', sa.String(length=50), nullable=False),
    sa.Column('environment_variables', postgresql.JSON(astext_type=Text()), nullable=False),
    sa.Column('custom_configuration', postgresql.JSON(astext_type=Text()), nullable=False),
    sa.Column('deployment_started_at', sa.DateTime(), nullable=True),
    sa.Column('deployment_completed_at', sa.DateTime(), nullable=True),
    sa.Column('last_update_at', sa.DateTime(), nullable=True),
    sa.Column('last_health_check', sa.DateTime(), nullable=True),
    sa.Column('health_status', sa.String(length=20), nullable=False),
    sa.Column('health_details', postgresql.JSON(astext_type=Text()), nullable=False),
    sa.Column('current_hourly_cost_cents', sa.Integer(), nullable=False),
    sa.Column('estimated_monthly_cost_cents', sa.Integer(), nullable=False),
    sa.Column('actual_monthly_cost_cents', sa.Integer(), nullable=False),
    sa.Column('min_instances', sa.Integer(), nullable=False),
    sa.Column('max_instances', sa.Integer(), nullable=False),
    sa.Column('current_instances', sa.Integer(), nullable=False),
    sa.Column('auto_scaling_enabled', sa.Boolean(), nullable=False),
    sa.Column('backup_enabled', sa.Boolean(), nullable=False),
    sa.Column('backup_retention_days', sa.Integer(), nullable=False),
    sa.Column('last_backup_at', sa.DateTime(), nullable=True),
    sa.Column('monitoring_enabled', sa.Boolean(), nullable=False),
    sa.Column('alerting_enabled', sa.Boolean(), nullable=False),
    sa.Column('cloud_resource_id', sa.String(length=255), nullable=True),
    sa.Column('kubernetes_namespace', sa.String(length=255), nullable=True),
    sa.Column('load_balancer_id', sa.String(length=255), nullable=True),
    sa.Column('deployment_logs', postgresql.JSON(astext_type=Text()), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_by', GUID(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['infrastructure_template_id'], ['infrastructure_templates.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['customer_tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deployments_cloud_provider'), 'deployments', ['cloud_provider'], unique=False)
    op.create_index(op.f('ix_deployments_domain_name'), 'deployments', ['domain_name'], unique=False)
    op.create_index(op.f('ix_deployments_id'), 'deployments', ['id'], unique=False)
    op.create_index(op.f('ix_deployments_is_deleted'), 'deployments', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_deployments_name'), 'deployments', ['name'], unique=False)
    op.create_index(op.f('ix_deployments_resource_tier'), 'deployments', ['resource_tier'], unique=False)
    op.create_index(op.f('ix_deployments_slug'), 'deployments', ['slug'], unique=False)
    op.create_index(op.f('ix_deployments_status'), 'deployments', ['status'], unique=False)
    op.create_index(op.f('ix_deployments_tenant_id'), 'deployments', ['tenant_id'], unique=False)
    op.create_table('plugins',
    sa.Column('category_id', GUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('short_description', sa.String(length=500), nullable=False),
    sa.Column('full_description', sa.Text(), nullable=True),
    sa.Column('features', postgresql.JSON(astext_type=Text()), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=False),
    sa.Column('website_url', sa.String(length=500), nullable=True),
    sa.Column('documentation_url', sa.String(length=500), nullable=True),
    sa.Column('support_url', sa.String(length=500), nullable=True),
    sa.Column('min_dotmac_version', sa.String(length=50), nullable=False),
    sa.Column('max_dotmac_version', sa.String(length=50), nullable=True),
    sa.Column('dependencies', postgresql.JSON(astext_type=Text()), nullable=False),
    sa.Column('icon_url', sa.String(length=500), nullable=True),
    sa.Column('screenshot_urls', postgresql.JSON(astext_type=Text()), nullable=False),
    sa.Column('download_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'DEPRECATED', 'DISCONTINUED', name='pluginstatus'), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('download_count', sa.Integer(), nullable=False),
    sa.Column('active_installations', sa.Integer(), nullable=False),
    sa.Column('rating_average', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('rating_count', sa.Integer(), nullable=False),
    sa.Column('free_tier_available', sa.Boolean(), nullable=False),
    sa.Column('basic_price_cents', sa.Integer(), nullable=False),
    sa.Column('premium_price_cents', sa.Integer(), nullable=False),
    sa.Column('enterprise_price_cents', sa.Integer(), nullable=False),
    sa.Column('usage_based_pricing', sa.Boolean(), nullable=False),
    sa.Column('usage_price_per_unit_cents', sa.Integer(), nullable=False),
    sa.Column('usage_unit', sa.String(length=50), nullable=True),
    sa.Column('trial_days', sa.Integer(), nullable=False),
    sa.Column('default_configuration', postgresql.JSON(astext_type=Text()), nullable=False),
    sa.Column('configuration_schema', postgresql.JSON(astext_type=Text()), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['plugin_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plugins_category_id'), 'plugins', ['category_id'], unique=False)
    op.create_index(op.f('ix_plugins_id'), 'plugins', ['id'], unique=False)
    op.create_index(op.f('ix_plugins_is_deleted'), 'plugins', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_plugins_is_featured'), 'plugins', ['is_featured'], unique=False)
    op.create_index(op.f('ix_plugins_name'), 'plugins', ['name'], unique=False)
    op.create_index(op.f('ix_plugins_slug'), 'plugins', ['slug'], unique=True)
    op.create_index(op.f('ix_plugins_status'), 'plugins', ['status'], unique=False)
    op.create_table('subscriptions',
    sa.Column('tenant_id', GUID(), nullable=False),
    sa.Column('pricing_plan_id', GUID(), nullable=False),
    sa.Column('status', sa.Enum('TRIAL', 'ACTIVE', 'PAST_DUE', 'CANCELLED', 'UNPAID', 'PAUSED', name='subscriptionstatus'), nullable=False),
    sa.Column('current_period_start', sa.DateTime(), nullable=False),
    sa.Column('current_period_end', sa.DateTime(), nullable=False),
    sa.Column('trial_start', sa.DateTime(), nullable=True),
    sa.Column('trial_end', sa.DateTime(), nullable=True),
    sa.Column('billing_cycle_day', sa.Integer(), nullable=False),
    sa.Column('cancel_at_period_end', sa.Boolean(), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('cancel_reason', sa.String(length=500), nullable=True),
    sa.Column('current_usage', postgresql.JSON(astext_type=Text()), nullable=False),
    sa.Column('default_payment_method_id', GUID(), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['pricing_plan_id'], ['pricing_plans.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['customer_tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_current_period_end'), 'subscriptions', ['current_period_end'], unique=False)
    op.create_index(op.f('ix_subscriptions_current_period_start'), 'subscriptions', ['current_period_start'], unique=False)
    op.create_index(op.f('ix_subscriptions_id'), 'subscriptions', ['id'], unique=False)
    op.create_index(op.f('ix_subscriptions_is_deleted'), 'subscriptions', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_subscriptions_status'), 'subscriptions', ['status'], unique=False)
    op.create_index(op.f('ix_subscriptions_stripe_subscription_id'), 'subscriptions', ['stripe_subscription_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_tenant_id'), 'subscriptions', ['tenant_id'], unique=False)
    op.create_table('user_invitations',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('tenant_id', GUID(), nullable=True),
    sa.Column('invitation_token', sa.String(length=255), nullable=False),
    sa.Column('invited_by', GUID(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_accepted', sa.Boolean(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.Column('accepted_by', GUID(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['accepted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['customer_tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_invitations_email'), 'user_invitations', ['email'], unique=False)
    op.create_index(op.f('ix_user_invitations_expires_at'), 'user_invitations', ['expires_at'], unique=False)
    op.create_index(op.f('ix_user_invitations_id'), 'user_invitations', ['id'], unique=False)
    op.create_index(op.f('ix_user_invitations_invitation_token'), 'user_invitations', ['invitation_token'], unique=True)
    op.create_index(op.f('ix_user_invitations_is_deleted'), 'user_invitations', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_user_invitations_tenant_id'), 'user_invitations', ['tenant_id'], unique=False)
    op.create_table('user_sessions',
    sa.Column('user_id', GUID(), nullable=False),
    sa.Column('session_token', sa.String(length=255), nullable=False),
    sa.Column('refresh_token', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('device_fingerprint', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('last_activity', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_sessions_expires_at'), 'user_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_user_sessions_id'), 'user_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_user_sessions_is_active'), 'user_sessions', ['is_active'], unique=False)
    op.create_index(op.f('ix_user_sessions_is_deleted'), 'user_sessions', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_user_sessions_refresh_token'), 'user_sessions', ['refresh_token'], unique=True)
    op.create_index(op.f('ix_user_sessions_session_token'), 'user_sessions', ['session_token'], unique=True)
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.create_table('vps_customers',
    sa.Column('customer_id', sa.String(length=100), nullable=False),
    sa.Column('subdomain', sa.String(length=100), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('admin_email', sa.String(length=255), nullable=False),
    sa.Column('admin_name', sa.String(length=200), nullable=False),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('plan', sa.String(length=50), nullable=False),
    sa.Column('support_tier', sa.String(length=50), nullable=False),
    sa.Column('vps_ip', sa.String(length=45), nullable=False),
    sa.Column('ssh_port', sa.Integer(), nullable=True),
    sa.Column('ssh_username', sa.String(length=100), nullable=False),
    sa.Column('ssh_key', sa.Text(), nullable=True),
    sa.Column('ssh_password_hash', sa.String(length=255), nullable=True),
    sa.Column('custom_domain', sa.String(length=255), nullable=True),
    sa.Column('expected_customers', sa.Integer(), nullable=True),
    sa.Column('estimated_traffic', sa.String(length=20), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('preferred_backup_time', sa.String(length=10), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('deployment_logs', sa.JSON(), nullable=True),
    sa.Column('deployment_started_at', sa.DateTime(), nullable=True),
    sa.Column('deployment_completed_at', sa.DateTime(), nullable=True),
    sa.Column('last_health_check', sa.DateTime(), nullable=True),
    sa.Column('health_status', sa.String(length=50), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('deployment_config', sa.JSON(), nullable=True),
    sa.Column('last_support_contact', sa.DateTime(), nullable=True),
    sa.Column('support_ticket_count', sa.Integer(), nullable=True),
    sa.Column('satisfaction_score', sa.Integer(), nullable=True),
    sa.Column('billing_email', sa.String(length=255), nullable=True),
    sa.Column('payment_method_id', sa.String(length=100), nullable=True),
    sa.Column('subscription_id', sa.String(length=100), nullable=True),
    sa.Column('next_billing_date', sa.DateTime(), nullable=True),
    sa.Column('monthly_fee', sa.Integer(), nullable=True),
    sa.Column('setup_fee_paid', sa.Boolean(), nullable=True),
    sa.Column('monitoring_enabled', sa.Boolean(), nullable=True),
    sa.Column('alert_preferences', sa.JSON(), nullable=True),
    sa.Column('uptime_percentage', sa.String(length=10), nullable=True),
    sa.Column('sla_level', sa.String(length=50), nullable=True),
    sa.Column('sla_credits', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', GUID(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vps_customers_customer_id'), 'vps_customers', ['customer_id'], unique=True)
    op.create_index(op.f('ix_vps_customers_status'), 'vps_customers', ['status'], unique=False)
    op.create_index(op.f('ix_vps_customers_subdomain'), 'vps_customers', ['subdomain'], unique=True)
    op.create_table('alerts',
    sa.Column('tenant_id', GUID(), nullable=False),
    sa.Column('deployment_id', GUID(), nullable=True),
    sa.Column('alert_name', sa.String(length=255), nullable=False),
    sa.Column('alert_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'WARNING', 'CRITICAL', 'EMERGENCY', name='alertseverity'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'ACKNOWLEDGED', 'RESOLVED', 'SUPPRESSED', name='alertstatus'), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('metric_name', sa.String(length=255), nullable=True),
    sa.Column('threshold_value', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('threshold_operator', sa.String(length=10), nullable=True),
    sa.Column('current_value', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('first_triggered_at', sa.DateTime(), nullable=False),
    sa.Column('last_triggered_at', sa.DateTime(), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('evaluation_interval_seconds', sa.Integer(), nullable=False),
    sa.Column('suppression_duration_seconds', sa.Integer(), nullable=False),
    sa.Column('labels', postgresql.JSON(astext_type=Text()), nullable=False),
    sa.Column('annotations', postgresql.JSON(astext_type=Text()), nullable=False),
    sa.Column('notification_channels', postgresql.JSON(astext_type=Text()), nullable=False),
    sa.Column('notification_sent', sa.Boolean(), nullable=False),
    sa.Column('last_notification_at', sa.DateTime(), nullable=True),
    sa.Column('acknowledged_by', GUID(), nullable=True),
    sa.Column('resolved_by', GUID(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deployment_id'], ['deployments.id'], ),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['customer_tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_alert_name'), 'alerts', ['alert_name'], unique=False)
    op.create_index(op.f('ix_alerts_alert_type'), 'alerts', ['alert_type'], unique=False)
    op.create_index(op.f('ix_alerts_deployment_id'), 'alerts', ['deployment_id'], unique=False)
    op.create_index(op.f('ix_alerts_id'), 'alerts', ['id'], unique=False)
    op.create_index(op.f('ix_alerts_is_deleted'), 'alerts', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_alerts_metric_name'), 'alerts', ['metric_name'], unique=False)
    op.create_index(op.f('ix_alerts_severity'), 'alerts', ['severity'], unique=False)
    op.create_index(op.f('ix_alerts_status'), 'alerts', ['status'], unique=False)
    op.create_index(op.f('ix_alerts_tenant_id'), 'alerts', ['tenant_id'], unique=False)
    op.create_table('deployment_events',
    sa.Column('deployment_id', GUID(), nullable=False),
    sa.Column('event_type', sa.Enum('CREATED', 'STARTED', 'PROVISIONED', 'DEPLOYED', 'UPDATED', 'SCALED', 'STOPPED', 'FAILED', 'DELETED', name='deploymenteventtype'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_success', sa.Boolean(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('event_data', postgresql.JSON(astext_type=Text()), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('triggered_by', GUID(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['deployment_id'], ['deployments.id'], ),
    sa.ForeignKeyConstraint(['triggered_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deployment_events_deployment_id'), 'deployment_events', ['deployment_id'], unique=False)
    op.create_index(op.f('ix_deployment_events_event_type'), 'deployment_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_deployment_events_id'), 'deployment_events', ['id'], unique=False)
    op.create_index(op.f('ix_deployment_events_is_deleted'), 'deployment_events', ['is_deleted'], unique=False)
    op.create_table('deployment_resources',
    sa.Column('deployment_id', GUID(), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('resource_name', sa.String(length=255), nullable=False),
    sa.Column('resource_id', sa.String(length=255), nullable=False),
    sa.Column('configuration', postgresql.JSON(astext_type=Text()), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('hourly_cost_cents', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['deployment_id'], ['deployments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deployment_resources_deployment_id'), 'deployment_resources', ['deployment_id'], unique=False)
    op.create_index(op.f('ix_deployment_resources_id'), 'deployment_resources', ['id'], unique=False)
    op.create_index(op.f('ix_deployment_resources_is_deleted'), 'deployment_resources', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_deployment_resources_resource_type'), 'deployment_resources', ['resource_type'], unique=False)
    op.create_table('health_checks',
    sa.Column('tenant_id', GUID(), nullable=False),
    sa.Column('deployment_id', GUID(), nullable=True),
    sa.Column('check_name', sa.String(length=255), nullable=False),
    sa.Column('check_type', sa.String(length=100), nullable=False),
    sa.Column('endpoint_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('HEALTHY', 'WARNING', 'CRITICAL', 'UNKNOWN', name='healthstatus'), nullable=False),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('response_data', postgresql.JSON(astext_type=Text()), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('check_interval_seconds', sa.Integer(), nullable=False),
    sa.Column('check_details', postgresql.JSON(astext_type=Text()), nullable=False),
    sa.Column('tags', postgresql.JSON(astext_type=Text()), nullable=False),
    sa.Column('next_check_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['deployment_id'], ['deployments.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['customer_tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_checks_check_name'), 'health_checks', ['check_name'], unique=False)
    op.create_index(op.f('ix_health_checks_check_type'), 'health_checks', ['check_type'], unique=False)
    op.create_index(op.f('ix_health_checks_deployment_id'), 'health_checks', ['deployment_id'], unique=False)
    op.create_index(op.f('ix_health_checks_id'), 'health_checks', ['id'], unique=False)
    op.create_index(op.f('ix_health_checks_is_deleted'), 'health_checks', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_health_checks_next_check_at'), 'health_checks', ['next_check_at'], unique=False)
    op.create_index(op.f('ix_health_checks_status'), 'health_checks', ['status'], unique=False)
    op.create_index(op.f('ix_health_checks_success'), 'health_checks', ['success'], unique=False)
    op.create_index(op.f('ix_health_checks_tenant_id'), 'health_checks', ['tenant_id'], unique=False)
    op.create_table('invoices',
    sa.Column('subscription_id', GUID(), nullable=False),
    sa.Column('invoice_number', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SENT', 'PAID', 'OVERDUE', 'CANCELLED', 'REFUNDED', name='invoicestatus'), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('subtotal_cents', sa.Integer(), nullable=False),
    sa.Column('tax_cents', sa.Integer(), nullable=False),
    sa.Column('total_cents', sa.Integer(), nullable=False),
    sa.Column('amount_paid_cents', sa.Integer(), nullable=False),
    sa.Column('amount_due_cents', sa.Integer(), nullable=False),
    sa.Column('invoice_date', sa.DateTime(), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('line_items', postgresql.JSON(astext_type=Text()), nullable=False),
    sa.Column('payment_attempted', sa.Boolean(), nullable=False),
    sa.Column('payment_attempts', sa.Integer(), nullable=False),
    sa.Column('next_payment_attempt', sa.DateTime(), nullable=True),
    sa.Column('stripe_invoice_id', sa.String(length=255), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_id'), 'invoices', ['id'], unique=False)
    op.create_index(op.f('ix_invoices_invoice_number'), 'invoices', ['invoice_number'], unique=True)
    op.create_index(op.f('ix_invoices_is_deleted'), 'invoices', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_invoices_status'), 'invoices', ['status'], unique=False)
    op.create_index(op.f('ix_invoices_stripe_invoice_id'), 'invoices', ['stripe_invoice_id'], unique=False)
    op.create_index(op.f('ix_invoices_subscription_id'), 'invoices', ['subscription_id'], unique=False)
    op.create_table('metrics',
    sa.Column('tenant_id', GUID(), nullable=False),
    sa.Column('deployment_id', GUID(), nullable=True),
    sa.Column('metric_name', sa.String(length=255), nullable=False),
    sa.Column('metric_type', sa.Enum('COUNTER', 'GAUGE', 'HISTOGRAM', 'SUMMARY', name='metrictype'), nullable=False),
    sa.Column('value', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('labels', postgresql.JSON(astext_type=Text()), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('host', sa.String(length=255), nullable=True),
    sa.Column('period_seconds', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['deployment_id'], ['deployments.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['customer_tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metrics_deployment_id'), 'metrics', ['deployment_id'], unique=False)
    op.create_index(op.f('ix_metrics_id'), 'metrics', ['id'], unique=False)
    op.create_index(op.f('ix_metrics_is_deleted'), 'metrics', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_metrics_metric_name'), 'metrics', ['metric_name'], unique=False)
    op.create_index(op.f('ix_metrics_metric_type'), 'metrics', ['metric_type'], unique=False)
    op.create_index(op.f('ix_metrics_tenant_id'), 'metrics', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_metrics_timestamp'), 'metrics', ['timestamp'], unique=False)
    op.create_table('plugin_licenses',
    sa.Column('tenant_id', GUID(), nullable=False),
    sa.Column('plugin_id', GUID(), nullable=False),
    sa.Column('license_tier', sa.Enum('FREE', 'BASIC', 'PREMIUM', 'ENTERPRISE', name='licensetier'), nullable=False),
    sa.Column('status', sa.Enum('TRIAL', 'ACTIVE', 'SUSPENDED', 'EXPIRED', 'CANCELLED', name='licensestatus'), nullable=False),
    sa.Column('activated_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('trial_ends_at', sa.DateTime(), nullable=True),
    sa.Column('usage_limit', sa.Integer(), nullable=True),
    sa.Column('current_usage', sa.Integer(), nullable=False),
    sa.Column('configuration', postgresql.JSON(astext_type=Text()), nullable=False),
    sa.Column('feature_flags', postgresql.JSON(astext_type=Text()), nullable=False),
    sa.Column('subscription_id', GUID(), nullable=True),
    sa.Column('last_billing_date', sa.DateTime(), nullable=True),
    sa.Column('next_billing_date', sa.DateTime(), nullable=True),
    sa.Column('license_key', sa.String(length=255), nullable=True),
    sa.Column('installation_count', sa.Integer(), nullable=False),
    sa.Column('max_installations', sa.Integer(), nullable=False),
    sa.Column('auto_renew', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['plugin_id'], ['plugins.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['customer_tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plugin_licenses_expires_at'), 'plugin_licenses', ['expires_at'], unique=False)
    op.create_index(op.f('ix_plugin_licenses_id'), 'plugin_licenses', ['id'], unique=False)
    op.create_index(op.f('ix_plugin_licenses_is_deleted'), 'plugin_licenses', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_plugin_licenses_license_key'), 'plugin_licenses', ['license_key'], unique=False)
    op.create_index(op.f('ix_plugin_licenses_license_tier'), 'plugin_licenses', ['license_tier'], unique=False)
    op.create_index(op.f('ix_plugin_licenses_plugin_id'), 'plugin_licenses', ['plugin_id'], unique=False)
    op.create_index(op.f('ix_plugin_licenses_status'), 'plugin_licenses', ['status'], unique=False)
    op.create_index(op.f('ix_plugin_licenses_tenant_id'), 'plugin_licenses', ['tenant_id'], unique=False)
    op.create_table('sla_records',
    sa.Column('tenant_id', GUID(), nullable=False),
    sa.Column('deployment_id', GUID(), nullable=True),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('period_type', sa.String(length=20), nullable=False),
    sa.Column('uptime_percentage', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('availability_percentage', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('response_time_avg_ms', sa.Integer(), nullable=False),
    sa.Column('response_time_95p_ms', sa.Integer(), nullable=False),
    sa.Column('error_rate_percentage', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('uptime_target_percentage', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('response_time_target_ms', sa.Integer(), nullable=False),
    sa.Column('error_rate_target_percentage', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('uptime_met', sa.Boolean(), nullable=False),
    sa.Column('response_time_met', sa.Boolean(), nullable=False),
    sa.Column('error_rate_met', sa.Boolean(), nullable=False),
    sa.Column('overall_sla_met', sa.Boolean(), nullable=False),
    sa.Column('incident_count', sa.Integer(), nullable=False),
    sa.Column('total_downtime_minutes', sa.Integer(), nullable=False),
    sa.Column('mttr_minutes', sa.Integer(), nullable=True),
    sa.Column('credit_percentage', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('credit_amount_cents', sa.Integer(), nullable=False),
    sa.Column('credit_applied', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['deployment_id'], ['deployments.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['customer_tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sla_records_deployment_id'), 'sla_records', ['deployment_id'], unique=False)
    op.create_index(op.f('ix_sla_records_id'), 'sla_records', ['id'], unique=False)
    op.create_index(op.f('ix_sla_records_is_deleted'), 'sla_records', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_sla_records_period_end'), 'sla_records', ['period_end'], unique=False)
    op.create_index(op.f('ix_sla_records_period_start'), 'sla_records', ['period_start'], unique=False)
    op.create_index(op.f('ix_sla_records_tenant_id'), 'sla_records', ['tenant_id'], unique=False)
    op.create_table('vps_deployment_events',
    sa.Column('event_id', sa.String(length=100), nullable=False),
    sa.Column('vps_customer_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=True),
    sa.Column('step_number', sa.Integer(), nullable=True),
    sa.Column('correlation_id', sa.String(length=100), nullable=True),
    sa.Column('operator', sa.String(length=100), nullable=True),
    sa.Column('command_executed', sa.Text(), nullable=True),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('stdout_output', sa.Text(), nullable=True),
    sa.Column('stderr_output', sa.Text(), nullable=True),
    sa.Column('execution_time_seconds', sa.Integer(), nullable=True),
    sa.Column('error_details', sa.JSON(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', GUID(), nullable=False),
    sa.ForeignKeyConstraint(['vps_customer_id'], ['vps_customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vps_deployment_events_event_id'), 'vps_deployment_events', ['event_id'], unique=True)
    op.create_table('vps_health_checks',
    sa.Column('vps_customer_id', sa.Integer(), nullable=False),
    sa.Column('check_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('check_duration_ms', sa.Integer(), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('check_source', sa.String(length=50), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', GUID(), nullable=False),
    sa.ForeignKeyConstraint(['vps_customer_id'], ['vps_customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vps_support_tickets',
    sa.Column('ticket_id', sa.String(length=50), nullable=False),
    sa.Column('vps_customer_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('customer_contact_name', sa.String(length=200), nullable=True),
    sa.Column('customer_contact_email', sa.String(length=255), nullable=True),
    sa.Column('customer_contact_phone', sa.String(length=50), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('customer_satisfaction', sa.Integer(), nullable=True),
    sa.Column('internal_notes', sa.JSON(), nullable=True),
    sa.Column('customer_communication', sa.JSON(), nullable=True),
    sa.Column('escalated', sa.Boolean(), nullable=True),
    sa.Column('escalated_at', sa.DateTime(), nullable=True),
    sa.Column('escalated_to', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', GUID(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['escalated_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vps_customer_id'], ['vps_customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vps_support_tickets_ticket_id'), 'vps_support_tickets', ['ticket_id'], unique=True)
    op.create_table('commissions',
    sa.Column('reseller_id', GUID(), nullable=False),
    sa.Column('tenant_id', GUID(), nullable=False),
    sa.Column('subscription_id', GUID(), nullable=True),
    sa.Column('invoice_id', GUID(), nullable=True),
    sa.Column('base_amount_cents', sa.Integer(), nullable=False),
    sa.Column('commission_rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('commission_amount_cents', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'PAID', 'CANCELLED', name='commissionstatus'), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('earned_date', sa.DateTime(), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('payment_reference', sa.String(length=255), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['reseller_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['customer_tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commissions_id'), 'commissions', ['id'], unique=False)
    op.create_index(op.f('ix_commissions_is_deleted'), 'commissions', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_commissions_reseller_id'), 'commissions', ['reseller_id'], unique=False)
    op.create_index(op.f('ix_commissions_status'), 'commissions', ['status'], unique=False)
    op.create_index(op.f('ix_commissions_tenant_id'), 'commissions', ['tenant_id'], unique=False)
    op.create_table('payments',
    sa.Column('invoice_id', GUID(), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'SUCCEEDED', 'FAILED', 'CANCELLED', 'REFUNDED', name='paymentstatus'), nullable=False),
    sa.Column('payment_method_type', sa.String(length=50), nullable=False),
    sa.Column('payment_method_details', postgresql.JSON(astext_type=Text()), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('failed_at', sa.DateTime(), nullable=True),
    sa.Column('failure_reason', sa.String(length=500), nullable=True),
    sa.Column('stripe_payment_intent_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_charge_id', sa.String(length=255), nullable=True),
    sa.Column('processor_fee_cents', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.create_index(op.f('ix_payments_invoice_id'), 'payments', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_payments_is_deleted'), 'payments', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_index(op.f('ix_payments_stripe_payment_intent_id'), 'payments', ['stripe_payment_intent_id'], unique=False)
    op.create_table('plugin_usage',
    sa.Column('license_id', GUID(), nullable=False),
    sa.Column('plugin_id', GUID(), nullable=False),
    sa.Column('usage_date', sa.DateTime(), nullable=False),
    sa.Column('usage_type', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('feature_name', sa.String(length=255), nullable=True),
    sa.Column('endpoint', sa.String(length=255), nullable=True),
    sa.Column('user_id', GUID(), nullable=True),
    sa.Column('request_id', sa.String(length=255), nullable=True),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('billable', sa.Boolean(), nullable=False),
    sa.Column('unit_cost_cents', sa.Integer(), nullable=False),
    sa.Column('total_cost_cents', sa.Integer(), nullable=False),
    sa.Column('billed', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['license_id'], ['plugin_licenses.id'], ),
    sa.ForeignKeyConstraint(['plugin_id'], ['plugins.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plugin_usage_billed'), 'plugin_usage', ['billed'], unique=False)
    op.create_index(op.f('ix_plugin_usage_id'), 'plugin_usage', ['id'], unique=False)
    op.create_index(op.f('ix_plugin_usage_is_deleted'), 'plugin_usage', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_plugin_usage_license_id'), 'plugin_usage', ['license_id'], unique=False)
    op.create_index(op.f('ix_plugin_usage_plugin_id'), 'plugin_usage', ['plugin_id'], unique=False)
    op.create_index(op.f('ix_plugin_usage_usage_date'), 'plugin_usage', ['usage_date'], unique=False)
    op.create_index(op.f('ix_plugin_usage_usage_type'), 'plugin_usage', ['usage_type'], unique=False)
    op.create_table('usage_records',
    sa.Column('subscription_id', GUID(), nullable=False),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=15, scale=6), nullable=False),
    sa.Column('unit_price_cents', sa.Integer(), nullable=False),
    sa.Column('total_cost_cents', sa.Integer(), nullable=False),
    sa.Column('usage_date', sa.DateTime(), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('metadata_json', postgresql.JSON(astext_type=Text()), nullable=False),
    sa.Column('billed', sa.Boolean(), nullable=False),
    sa.Column('invoice_id', GUID(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_records_billed'), 'usage_records', ['billed'], unique=False)
    op.create_index(op.f('ix_usage_records_id'), 'usage_records', ['id'], unique=False)
    op.create_index(op.f('ix_usage_records_is_deleted'), 'usage_records', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_usage_records_metric_name'), 'usage_records', ['metric_name'], unique=False)
    op.create_index(op.f('ix_usage_records_subscription_id'), 'usage_records', ['subscription_id'], unique=False)
    op.create_index(op.f('ix_usage_records_usage_date'), 'usage_records', ['usage_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usage_records_usage_date'), table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_subscription_id'), table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_metric_name'), table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_is_deleted'), table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_id'), table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_billed'), table_name='usage_records')
    op.drop_table('usage_records')
    op.drop_index(op.f('ix_plugin_usage_usage_type'), table_name='plugin_usage')
    op.drop_index(op.f('ix_plugin_usage_usage_date'), table_name='plugin_usage')
    op.drop_index(op.f('ix_plugin_usage_plugin_id'), table_name='plugin_usage')
    op.drop_index(op.f('ix_plugin_usage_license_id'), table_name='plugin_usage')
    op.drop_index(op.f('ix_plugin_usage_is_deleted'), table_name='plugin_usage')
    op.drop_index(op.f('ix_plugin_usage_id'), table_name='plugin_usage')
    op.drop_index(op.f('ix_plugin_usage_billed'), table_name='plugin_usage')
    op.drop_table('plugin_usage')
    op.drop_index(op.f('ix_payments_stripe_payment_intent_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_is_deleted'), table_name='payments')
    op.drop_index(op.f('ix_payments_invoice_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_commissions_tenant_id'), table_name='commissions')
    op.drop_index(op.f('ix_commissions_status'), table_name='commissions')
    op.drop_index(op.f('ix_commissions_reseller_id'), table_name='commissions')
    op.drop_index(op.f('ix_commissions_is_deleted'), table_name='commissions')
    op.drop_index(op.f('ix_commissions_id'), table_name='commissions')
    op.drop_table('commissions')
    op.drop_index(op.f('ix_vps_support_tickets_ticket_id'), table_name='vps_support_tickets')
    op.drop_table('vps_support_tickets')
    op.drop_table('vps_health_checks')
    op.drop_index(op.f('ix_vps_deployment_events_event_id'), table_name='vps_deployment_events')
    op.drop_table('vps_deployment_events')
    op.drop_index(op.f('ix_sla_records_tenant_id'), table_name='sla_records')
    op.drop_index(op.f('ix_sla_records_period_start'), table_name='sla_records')
    op.drop_index(op.f('ix_sla_records_period_end'), table_name='sla_records')
    op.drop_index(op.f('ix_sla_records_is_deleted'), table_name='sla_records')
    op.drop_index(op.f('ix_sla_records_id'), table_name='sla_records')
    op.drop_index(op.f('ix_sla_records_deployment_id'), table_name='sla_records')
    op.drop_table('sla_records')
    op.drop_index(op.f('ix_plugin_licenses_tenant_id'), table_name='plugin_licenses')
    op.drop_index(op.f('ix_plugin_licenses_status'), table_name='plugin_licenses')
    op.drop_index(op.f('ix_plugin_licenses_plugin_id'), table_name='plugin_licenses')
    op.drop_index(op.f('ix_plugin_licenses_license_tier'), table_name='plugin_licenses')
    op.drop_index(op.f('ix_plugin_licenses_license_key'), table_name='plugin_licenses')
    op.drop_index(op.f('ix_plugin_licenses_is_deleted'), table_name='plugin_licenses')
    op.drop_index(op.f('ix_plugin_licenses_id'), table_name='plugin_licenses')
    op.drop_index(op.f('ix_plugin_licenses_expires_at'), table_name='plugin_licenses')
    op.drop_table('plugin_licenses')
    op.drop_index(op.f('ix_metrics_timestamp'), table_name='metrics')
    op.drop_index(op.f('ix_metrics_tenant_id'), table_name='metrics')
    op.drop_index(op.f('ix_metrics_metric_type'), table_name='metrics')
    op.drop_index(op.f('ix_metrics_metric_name'), table_name='metrics')
    op.drop_index(op.f('ix_metrics_is_deleted'), table_name='metrics')
    op.drop_index(op.f('ix_metrics_id'), table_name='metrics')
    op.drop_index(op.f('ix_metrics_deployment_id'), table_name='metrics')
    op.drop_table('metrics')
    op.drop_index(op.f('ix_invoices_subscription_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_stripe_invoice_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_status'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_is_deleted'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_invoice_number'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_health_checks_tenant_id'), table_name='health_checks')
    op.drop_index(op.f('ix_health_checks_success'), table_name='health_checks')
    op.drop_index(op.f('ix_health_checks_status'), table_name='health_checks')
    op.drop_index(op.f('ix_health_checks_next_check_at'), table_name='health_checks')
    op.drop_index(op.f('ix_health_checks_is_deleted'), table_name='health_checks')
    op.drop_index(op.f('ix_health_checks_id'), table_name='health_checks')
    op.drop_index(op.f('ix_health_checks_deployment_id'), table_name='health_checks')
    op.drop_index(op.f('ix_health_checks_check_type'), table_name='health_checks')
    op.drop_index(op.f('ix_health_checks_check_name'), table_name='health_checks')
    op.drop_table('health_checks')
    op.drop_index(op.f('ix_deployment_resources_resource_type'), table_name='deployment_resources')
    op.drop_index(op.f('ix_deployment_resources_is_deleted'), table_name='deployment_resources')
    op.drop_index(op.f('ix_deployment_resources_id'), table_name='deployment_resources')
    op.drop_index(op.f('ix_deployment_resources_deployment_id'), table_name='deployment_resources')
    op.drop_table('deployment_resources')
    op.drop_index(op.f('ix_deployment_events_is_deleted'), table_name='deployment_events')
    op.drop_index(op.f('ix_deployment_events_id'), table_name='deployment_events')
    op.drop_index(op.f('ix_deployment_events_event_type'), table_name='deployment_events')
    op.drop_index(op.f('ix_deployment_events_deployment_id'), table_name='deployment_events')
    op.drop_table('deployment_events')
    op.drop_index(op.f('ix_alerts_tenant_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_status'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_severity'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_metric_name'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_is_deleted'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_deployment_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_alert_type'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_alert_name'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_vps_customers_subdomain'), table_name='vps_customers')
    op.drop_index(op.f('ix_vps_customers_status'), table_name='vps_customers')
    op.drop_index(op.f('ix_vps_customers_customer_id'), table_name='vps_customers')
    op.drop_table('vps_customers')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_session_token'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_refresh_token'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_is_deleted'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_is_active'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_expires_at'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_user_invitations_tenant_id'), table_name='user_invitations')
    op.drop_index(op.f('ix_user_invitations_is_deleted'), table_name='user_invitations')
    op.drop_index(op.f('ix_user_invitations_invitation_token'), table_name='user_invitations')
    op.drop_index(op.f('ix_user_invitations_id'), table_name='user_invitations')
    op.drop_index(op.f('ix_user_invitations_expires_at'), table_name='user_invitations')
    op.drop_index(op.f('ix_user_invitations_email'), table_name='user_invitations')
    op.drop_table('user_invitations')
    op.drop_index(op.f('ix_subscriptions_tenant_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_stripe_subscription_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_status'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_is_deleted'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_current_period_start'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_current_period_end'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_plugins_status'), table_name='plugins')
    op.drop_index(op.f('ix_plugins_slug'), table_name='plugins')
    op.drop_index(op.f('ix_plugins_name'), table_name='plugins')
    op.drop_index(op.f('ix_plugins_is_featured'), table_name='plugins')
    op.drop_index(op.f('ix_plugins_is_deleted'), table_name='plugins')
    op.drop_index(op.f('ix_plugins_id'), table_name='plugins')
    op.drop_index(op.f('ix_plugins_category_id'), table_name='plugins')
    op.drop_table('plugins')
    op.drop_index(op.f('ix_deployments_tenant_id'), table_name='deployments')
    op.drop_index(op.f('ix_deployments_status'), table_name='deployments')
    op.drop_index(op.f('ix_deployments_slug'), table_name='deployments')
    op.drop_index(op.f('ix_deployments_resource_tier'), table_name='deployments')
    op.drop_index(op.f('ix_deployments_name'), table_name='deployments')
    op.drop_index(op.f('ix_deployments_is_deleted'), table_name='deployments')
    op.drop_index(op.f('ix_deployments_id'), table_name='deployments')
    op.drop_index(op.f('ix_deployments_domain_name'), table_name='deployments')
    op.drop_index(op.f('ix_deployments_cloud_provider'), table_name='deployments')
    op.drop_table('deployments')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index(op.f('ix_users_is_deleted'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_pricing_plans_stripe_price_id'), table_name='pricing_plans')
    op.drop_index(op.f('ix_pricing_plans_slug'), table_name='pricing_plans')
    op.drop_index(op.f('ix_pricing_plans_plan_type'), table_name='pricing_plans')
    op.drop_index(op.f('ix_pricing_plans_name'), table_name='pricing_plans')
    op.drop_index(op.f('ix_pricing_plans_is_deleted'), table_name='pricing_plans')
    op.drop_index(op.f('ix_pricing_plans_is_active'), table_name='pricing_plans')
    op.drop_index(op.f('ix_pricing_plans_id'), table_name='pricing_plans')
    op.drop_table('pricing_plans')
    op.drop_index(op.f('ix_plugin_categories_slug'), table_name='plugin_categories')
    op.drop_index(op.f('ix_plugin_categories_name'), table_name='plugin_categories')
    op.drop_index(op.f('ix_plugin_categories_is_deleted'), table_name='plugin_categories')
    op.drop_index(op.f('ix_plugin_categories_is_active'), table_name='plugin_categories')
    op.drop_index(op.f('ix_plugin_categories_id'), table_name='plugin_categories')
    op.drop_table('plugin_categories')
    op.drop_index(op.f('ix_infrastructure_templates_resource_tier'), table_name='infrastructure_templates')
    op.drop_index(op.f('ix_infrastructure_templates_name'), table_name='infrastructure_templates')
    op.drop_index(op.f('ix_infrastructure_templates_is_deleted'), table_name='infrastructure_templates')
    op.drop_index(op.f('ix_infrastructure_templates_is_active'), table_name='infrastructure_templates')
    op.drop_index(op.f('ix_infrastructure_templates_id'), table_name='infrastructure_templates')
    op.drop_index(op.f('ix_infrastructure_templates_cloud_provider'), table_name='infrastructure_templates')
    op.drop_table('infrastructure_templates')
    op.drop_index(op.f('ix_customer_tenants_tenant_id'), table_name='customer_tenants')
    op.drop_index(op.f('ix_customer_tenants_subdomain'), table_name='customer_tenants')
    op.drop_index(op.f('ix_customer_tenants_status'), table_name='customer_tenants')
    op.drop_table('customer_tenants')
    # ### end Alembic commands ###