"""add commission config and partner branding models

Revision ID: 952b95951dab
Revises: 90ab336e04eb
Create Date: 2025-09-01 17:54:13.475219

"""
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

from alembic import op

# revision identifiers, used by Alembic.
revision = '952b95951dab'
down_revision = '90ab336e04eb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vps_customers_customer_id'), table_name='vps_customers')
    op.drop_index(op.f('ix_vps_customers_status'), table_name='vps_customers')
    op.drop_index(op.f('ix_vps_customers_subdomain'), table_name='vps_customers')
    op.drop_table('vps_customers')
    op.drop_index(op.f('ix_vps_support_tickets_ticket_id'), table_name='vps_support_tickets')
    op.drop_table('vps_support_tickets')
    op.drop_table('vps_health_checks')
    op.drop_index(op.f('ix_vps_deployment_events_event_id'), table_name='vps_deployment_events')
    op.drop_table('vps_deployment_events')
    op.alter_column('alerts', 'tenant_id',
               existing_type=sa.CHAR(length=32),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('alerts', 'deployment_id',
               existing_type=sa.CHAR(length=32),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('alerts', 'acknowledged_by',
               existing_type=sa.CHAR(length=32),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('alerts', 'resolved_by',
               existing_type=sa.CHAR(length=32),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('alerts', 'id',
               existing_type=sa.CHAR(length=32),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('commissions', 'reseller_id',
               existing_type=sa.CHAR(length=32),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('commissions', 'tenant_id',
               existing_type=sa.CHAR(length=32),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('commissions', 'subscription_id',
               existing_type=sa.CHAR(length=32),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('commissions', 'invoice_id',
               existing_type=sa.CHAR(length=32),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('commissions', 'id',
               existing_type=sa.CHAR(length=32),
               type_=sa.UUID(),
               existing_nullable=False)
    op.add_column('customer_tenants', sa.Column('deployment_type', sa.String(length=50), nullable=False))
    op.add_column('customer_tenants', sa.Column('vps_ip', sa.String(length=45), nullable=True))
    op.add_column('customer_tenants', sa.Column('ssh_port', sa.Integer(), nullable=True))
    op.add_column('customer_tenants', sa.Column('ssh_username', sa.String(length=100), nullable=True))
    op.add_column('customer_tenants', sa.Column('ssh_key', sa.Text(), nullable=True))
    op.add_column('customer_tenants', sa.Column('ssh_password_hash', sa.String(length=255), nullable=True))
    op.add_column('customer_tenants', sa.Column('custom_domain', sa.String(length=255), nullable=True))
    op.add_column('customer_tenants', sa.Column('expected_customers', sa.Integer(), nullable=True))
    op.add_column('customer_tenants', sa.Column('estimated_traffic', sa.String(length=20), nullable=True))
    op.add_column('customer_tenants', sa.Column('timezone', sa.String(length=50), nullable=True))
    op.add_column('customer_tenants', sa.Column('preferred_backup_time', sa.String(length=10), nullable=True))
    op.add_column('customer_tenants', sa.Column('support_tier', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_customer_tenants_deployment_type'), 'customer_tenants', ['deployment_type'], unique=False)
    op.alter_column('deployment_events', 'deployment_id',
               existing_type=sa.CHAR(length=32),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('deployment_events', 'triggered_by',
               existing_type=sa.CHAR(length=32),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('deployment_events', 'id',
               existing_type=sa.CHAR(length=32),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('deployment_resources', 'deployment_id',
               existing_type=sa.CHAR(length=32),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('deployment_resources', 'id',
               existing_type=sa.CHAR(length=32),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('deployments', 'tenant_id',
               existing_type=sa.CHAR(length=32),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('deployments', 'infrastructure_template_id',
               existing_type=sa.CHAR(length=32),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('deployments', 'created_by',
               existing_type=sa.CHAR(length=32),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('deployments', 'id',
               existing_type=sa.CHAR(length=32),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('health_checks', 'tenant_id',
               existing_type=sa.CHAR(length=32),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('health_checks', 'deployment_id',
               existing_type=sa.CHAR(length=32),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('health_checks', 'id',
               existing_type=sa.CHAR(length=32),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('infrastructure_templates', 'id',
               existing_type=sa.CHAR(length=32),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('invoices', 'subscription_id',
               existing_type=sa.CHAR(length=32),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('invoices', 'id',
               existing_type=sa.CHAR(length=32),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('metrics', 'tenant_id',
               existing_type=sa.CHAR(length=32),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('metrics', 'deployment_id',
               existing_type=sa.CHAR(length=32),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('metrics', 'id',
               existing_type=sa.CHAR(length=32),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('payments', 'invoice_id',
               existing_type=sa.CHAR(length=32),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('payments', 'id',
               existing_type=sa.CHAR(length=32),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('plugin_categories', 'id',
               existing_type=sa.CHAR(length=32),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('plugin_licenses', 'tenant_id',
               existing_type=sa.CHAR(length=32),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('plugin_licenses', 'plugin_id',
               existing_type=sa.CHAR(length=32),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('plugin_licenses', 'subscription_id',
               existing_type=sa.CHAR(length=32),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('plugin_licenses', 'id',
               existing_type=sa.CHAR(length=32),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('plugin_usage', 'license_id',
               existing_type=sa.CHAR(length=32),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('plugin_usage', 'plugin_id',
               existing_type=sa.CHAR(length=32),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('plugin_usage', 'user_id',
               existing_type=sa.CHAR(length=32),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('plugin_usage', 'id',
               existing_type=sa.CHAR(length=32),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('plugins', 'category_id',
               existing_type=sa.CHAR(length=32),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('plugins', 'id',
               existing_type=sa.CHAR(length=32),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('pricing_plans', 'id',
               existing_type=sa.CHAR(length=32),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('sla_records', 'tenant_id',
               existing_type=sa.CHAR(length=32),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('sla_records', 'deployment_id',
               existing_type=sa.CHAR(length=32),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('sla_records', 'id',
               existing_type=sa.CHAR(length=32),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('subscriptions', 'tenant_id',
               existing_type=sa.CHAR(length=32),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('subscriptions', 'pricing_plan_id',
               existing_type=sa.CHAR(length=32),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('subscriptions', 'default_payment_method_id',
               existing_type=sa.CHAR(length=32),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('subscriptions', 'id',
               existing_type=sa.CHAR(length=32),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('usage_records', 'subscription_id',
               existing_type=sa.CHAR(length=32),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('usage_records', 'invoice_id',
               existing_type=sa.CHAR(length=32),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('usage_records', 'id',
               existing_type=sa.CHAR(length=32),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('user_invitations', 'tenant_id',
               existing_type=sa.CHAR(length=32),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('user_invitations', 'invited_by',
               existing_type=sa.CHAR(length=32),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('user_invitations', 'accepted_by',
               existing_type=sa.CHAR(length=32),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('user_invitations', 'id',
               existing_type=sa.CHAR(length=32),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('user_sessions', 'user_id',
               existing_type=sa.CHAR(length=32),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('user_sessions', 'id',
               existing_type=sa.CHAR(length=32),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('users', 'tenant_id',
               existing_type=sa.CHAR(length=32),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('users', 'id',
               existing_type=sa.CHAR(length=32),
               type_=sa.UUID(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('users', 'tenant_id',
               existing_type=sa.UUID(),
               type_=sa.CHAR(length=32),
               existing_nullable=True)
    op.alter_column('user_sessions', 'id',
               existing_type=sa.UUID(),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('user_sessions', 'user_id',
               existing_type=sa.UUID(),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('user_invitations', 'id',
               existing_type=sa.UUID(),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('user_invitations', 'accepted_by',
               existing_type=sa.UUID(),
               type_=sa.CHAR(length=32),
               existing_nullable=True)
    op.alter_column('user_invitations', 'invited_by',
               existing_type=sa.UUID(),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('user_invitations', 'tenant_id',
               existing_type=sa.UUID(),
               type_=sa.CHAR(length=32),
               existing_nullable=True)
    op.alter_column('usage_records', 'id',
               existing_type=sa.UUID(),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('usage_records', 'invoice_id',
               existing_type=sa.UUID(),
               type_=sa.CHAR(length=32),
               existing_nullable=True)
    op.alter_column('usage_records', 'subscription_id',
               existing_type=sa.UUID(),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('subscriptions', 'id',
               existing_type=sa.UUID(),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('subscriptions', 'default_payment_method_id',
               existing_type=sa.UUID(),
               type_=sa.CHAR(length=32),
               existing_nullable=True)
    op.alter_column('subscriptions', 'pricing_plan_id',
               existing_type=sa.UUID(),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('subscriptions', 'tenant_id',
               existing_type=sa.UUID(),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('sla_records', 'id',
               existing_type=sa.UUID(),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('sla_records', 'deployment_id',
               existing_type=sa.UUID(),
               type_=sa.CHAR(length=32),
               existing_nullable=True)
    op.alter_column('sla_records', 'tenant_id',
               existing_type=sa.UUID(),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('pricing_plans', 'id',
               existing_type=sa.UUID(),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('plugins', 'id',
               existing_type=sa.UUID(),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('plugins', 'category_id',
               existing_type=sa.UUID(),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('plugin_usage', 'id',
               existing_type=sa.UUID(),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('plugin_usage', 'user_id',
               existing_type=sa.UUID(),
               type_=sa.CHAR(length=32),
               existing_nullable=True)
    op.alter_column('plugin_usage', 'plugin_id',
               existing_type=sa.UUID(),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('plugin_usage', 'license_id',
               existing_type=sa.UUID(),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('plugin_licenses', 'id',
               existing_type=sa.UUID(),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('plugin_licenses', 'subscription_id',
               existing_type=sa.UUID(),
               type_=sa.CHAR(length=32),
               existing_nullable=True)
    op.alter_column('plugin_licenses', 'plugin_id',
               existing_type=sa.UUID(),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('plugin_licenses', 'tenant_id',
               existing_type=sa.UUID(),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('plugin_categories', 'id',
               existing_type=sa.UUID(),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('payments', 'id',
               existing_type=sa.UUID(),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('payments', 'invoice_id',
               existing_type=sa.UUID(),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('metrics', 'id',
               existing_type=sa.UUID(),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('metrics', 'deployment_id',
               existing_type=sa.UUID(),
               type_=sa.CHAR(length=32),
               existing_nullable=True)
    op.alter_column('metrics', 'tenant_id',
               existing_type=sa.UUID(),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('invoices', 'id',
               existing_type=sa.UUID(),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('invoices', 'subscription_id',
               existing_type=sa.UUID(),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('infrastructure_templates', 'id',
               existing_type=sa.UUID(),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('health_checks', 'id',
               existing_type=sa.UUID(),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('health_checks', 'deployment_id',
               existing_type=sa.UUID(),
               type_=sa.CHAR(length=32),
               existing_nullable=True)
    op.alter_column('health_checks', 'tenant_id',
               existing_type=sa.UUID(),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('deployments', 'id',
               existing_type=sa.UUID(),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('deployments', 'created_by',
               existing_type=sa.UUID(),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('deployments', 'infrastructure_template_id',
               existing_type=sa.UUID(),
               type_=sa.CHAR(length=32),
               existing_nullable=True)
    op.alter_column('deployments', 'tenant_id',
               existing_type=sa.UUID(),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('deployment_resources', 'id',
               existing_type=sa.UUID(),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('deployment_resources', 'deployment_id',
               existing_type=sa.UUID(),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('deployment_events', 'id',
               existing_type=sa.UUID(),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('deployment_events', 'triggered_by',
               existing_type=sa.UUID(),
               type_=sa.CHAR(length=32),
               existing_nullable=True)
    op.alter_column('deployment_events', 'deployment_id',
               existing_type=sa.UUID(),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.drop_index(op.f('ix_customer_tenants_deployment_type'), table_name='customer_tenants')
    op.drop_column('customer_tenants', 'support_tier')
    op.drop_column('customer_tenants', 'preferred_backup_time')
    op.drop_column('customer_tenants', 'timezone')
    op.drop_column('customer_tenants', 'estimated_traffic')
    op.drop_column('customer_tenants', 'expected_customers')
    op.drop_column('customer_tenants', 'custom_domain')
    op.drop_column('customer_tenants', 'ssh_password_hash')
    op.drop_column('customer_tenants', 'ssh_key')
    op.drop_column('customer_tenants', 'ssh_username')
    op.drop_column('customer_tenants', 'ssh_port')
    op.drop_column('customer_tenants', 'vps_ip')
    op.drop_column('customer_tenants', 'deployment_type')
    op.alter_column('commissions', 'id',
               existing_type=sa.UUID(),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('commissions', 'invoice_id',
               existing_type=sa.UUID(),
               type_=sa.CHAR(length=32),
               existing_nullable=True)
    op.alter_column('commissions', 'subscription_id',
               existing_type=sa.UUID(),
               type_=sa.CHAR(length=32),
               existing_nullable=True)
    op.alter_column('commissions', 'tenant_id',
               existing_type=sa.UUID(),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('commissions', 'reseller_id',
               existing_type=sa.UUID(),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('alerts', 'id',
               existing_type=sa.UUID(),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('alerts', 'resolved_by',
               existing_type=sa.UUID(),
               type_=sa.CHAR(length=32),
               existing_nullable=True)
    op.alter_column('alerts', 'acknowledged_by',
               existing_type=sa.UUID(),
               type_=sa.CHAR(length=32),
               existing_nullable=True)
    op.alter_column('alerts', 'deployment_id',
               existing_type=sa.UUID(),
               type_=sa.CHAR(length=32),
               existing_nullable=True)
    op.alter_column('alerts', 'tenant_id',
               existing_type=sa.UUID(),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.create_table('vps_deployment_events',
    sa.Column('event_id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('vps_customer_id', sa.INTEGER(), nullable=False),
    sa.Column('event_type', sa.VARCHAR(length=100), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('message', sa.VARCHAR(length=500), nullable=True),
    sa.Column('step_number', sa.INTEGER(), nullable=True),
    sa.Column('correlation_id', sa.VARCHAR(length=100), nullable=True),
    sa.Column('operator', sa.VARCHAR(length=100), nullable=True),
    sa.Column('command_executed', sa.TEXT(), nullable=True),
    sa.Column('exit_code', sa.INTEGER(), nullable=True),
    sa.Column('stdout_output', sa.TEXT(), nullable=True),
    sa.Column('stderr_output', sa.TEXT(), nullable=True),
    sa.Column('execution_time_seconds', sa.INTEGER(), nullable=True),
    sa.Column('error_details', sqlite.JSON(), nullable=True),
    sa.Column('retry_count', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.ForeignKeyConstraint(['vps_customer_id'], ['vps_customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vps_deployment_events_event_id'), 'vps_deployment_events', ['event_id'], unique=1)
    op.create_table('vps_health_checks',
    sa.Column('vps_customer_id', sa.INTEGER(), nullable=False),
    sa.Column('check_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('check_duration_ms', sa.INTEGER(), nullable=True),
    sa.Column('response_time_ms', sa.INTEGER(), nullable=True),
    sa.Column('details', sqlite.JSON(), nullable=True),
    sa.Column('error_message', sa.VARCHAR(length=500), nullable=True),
    sa.Column('check_source', sa.VARCHAR(length=50), nullable=True),
    sa.Column('severity', sa.VARCHAR(length=20), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.ForeignKeyConstraint(['vps_customer_id'], ['vps_customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vps_support_tickets',
    sa.Column('ticket_id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('vps_customer_id', sa.INTEGER(), nullable=False),
    sa.Column('subject', sa.VARCHAR(length=255), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('priority', sa.VARCHAR(length=20), nullable=True),
    sa.Column('category', sa.VARCHAR(length=50), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('assigned_to', sa.INTEGER(), nullable=True),
    sa.Column('customer_contact_name', sa.VARCHAR(length=200), nullable=True),
    sa.Column('customer_contact_email', sa.VARCHAR(length=255), nullable=True),
    sa.Column('customer_contact_phone', sa.VARCHAR(length=50), nullable=True),
    sa.Column('resolution', sa.TEXT(), nullable=True),
    sa.Column('resolved_at', sa.DATETIME(), nullable=True),
    sa.Column('customer_satisfaction', sa.INTEGER(), nullable=True),
    sa.Column('internal_notes', sqlite.JSON(), nullable=True),
    sa.Column('customer_communication', sqlite.JSON(), nullable=True),
    sa.Column('escalated', sa.BOOLEAN(), nullable=True),
    sa.Column('escalated_at', sa.DATETIME(), nullable=True),
    sa.Column('escalated_to', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['escalated_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vps_customer_id'], ['vps_customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vps_support_tickets_ticket_id'), 'vps_support_tickets', ['ticket_id'], unique=1)
    op.create_table('vps_customers',
    sa.Column('customer_id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('subdomain', sa.VARCHAR(length=100), nullable=False),
    sa.Column('company_name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('admin_email', sa.VARCHAR(length=255), nullable=False),
    sa.Column('admin_name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('contact_phone', sa.VARCHAR(length=50), nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), nullable=False),
    sa.Column('plan', sa.VARCHAR(length=50), nullable=False),
    sa.Column('support_tier', sa.VARCHAR(length=50), nullable=False),
    sa.Column('vps_ip', sa.VARCHAR(length=45), nullable=False),
    sa.Column('ssh_port', sa.INTEGER(), nullable=True),
    sa.Column('ssh_username', sa.VARCHAR(length=100), nullable=False),
    sa.Column('ssh_key', sa.TEXT(), nullable=True),
    sa.Column('ssh_password_hash', sa.VARCHAR(length=255), nullable=True),
    sa.Column('custom_domain', sa.VARCHAR(length=255), nullable=True),
    sa.Column('expected_customers', sa.INTEGER(), nullable=True),
    sa.Column('estimated_traffic', sa.VARCHAR(length=20), nullable=True),
    sa.Column('timezone', sa.VARCHAR(length=50), nullable=True),
    sa.Column('preferred_backup_time', sa.VARCHAR(length=10), nullable=True),
    sa.Column('owner_id', sa.INTEGER(), nullable=False),
    sa.Column('deployment_logs', sqlite.JSON(), nullable=True),
    sa.Column('deployment_started_at', sa.DATETIME(), nullable=True),
    sa.Column('deployment_completed_at', sa.DATETIME(), nullable=True),
    sa.Column('last_health_check', sa.DATETIME(), nullable=True),
    sa.Column('health_status', sa.VARCHAR(length=50), nullable=True),
    sa.Column('settings', sqlite.JSON(), nullable=True),
    sa.Column('deployment_config', sqlite.JSON(), nullable=True),
    sa.Column('last_support_contact', sa.DATETIME(), nullable=True),
    sa.Column('support_ticket_count', sa.INTEGER(), nullable=True),
    sa.Column('satisfaction_score', sa.INTEGER(), nullable=True),
    sa.Column('billing_email', sa.VARCHAR(length=255), nullable=True),
    sa.Column('payment_method_id', sa.VARCHAR(length=100), nullable=True),
    sa.Column('subscription_id', sa.VARCHAR(length=100), nullable=True),
    sa.Column('next_billing_date', sa.DATETIME(), nullable=True),
    sa.Column('monthly_fee', sa.INTEGER(), nullable=True),
    sa.Column('setup_fee_paid', sa.BOOLEAN(), nullable=True),
    sa.Column('monitoring_enabled', sa.BOOLEAN(), nullable=True),
    sa.Column('alert_preferences', sqlite.JSON(), nullable=True),
    sa.Column('uptime_percentage', sa.VARCHAR(length=10), nullable=True),
    sa.Column('sla_level', sa.VARCHAR(length=50), nullable=True),
    sa.Column('sla_credits', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vps_customers_subdomain'), 'vps_customers', ['subdomain'], unique=1)
    op.create_index(op.f('ix_vps_customers_status'), 'vps_customers', ['status'], unique=False)
    op.create_index(op.f('ix_vps_customers_customer_id'), 'vps_customers', ['customer_id'], unique=1)
    # ### end Alembic commands ###