components:
  schemas:
    Error:
      properties:
        details:
          description: Additional error details
          type: object
        error:
          description: Error code
          type: string
        message:
          description: Error message
          type: string
      required:
      - error
      - message
      type: object
    PaginatedResponse:
      properties:
        has_next:
          description: Has next page
          type: boolean
        has_prev:
          description: Has previous page
          type: boolean
        items:
          items:
            type: object
          type: array
        page:
          description: Current page
          type: integer
        per_page:
          description: Items per page
          type: integer
        total:
          description: Total number of items
          type: integer
      type: object
  securitySchemes:
    apiKey:
      in: header
      name: X-API-Key
      type: apiKey
    bearerAuth:
      bearerFormat: JWT
      scheme: bearer
      type: http
info:
  contact:
    email: support@dotmac.io
    name: DotMac Platform Team
  description: Central API gateway with routing, rate limiting, and authentication
    proxy
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  title: API Gateway
  version: 1.0.0
openapi: 3.0.0
paths:
  /api/v1:
    get:
      description: Get API version and capabilities
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  capabilities:
                    items:
                      type: string
                    type: array
                  service:
                    example: API Gateway
                    type: string
                  version:
                    example: 1.0.0
                    type: string
                type: object
          description: API information
      summary: API Information
      tags:
      - API
  /health:
    get:
      description: Check service health status
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  service:
                    example: dotmac_api_gateway
                    type: string
                  status:
                    example: healthy
                    type: string
                  timestamp:
                    format: date-time
                    type: string
                  version:
                    example: 1.0.0
                    type: string
                type: object
          description: Service is healthy
      summary: Health Check
      tags:
      - Health
security:
- bearerAuth: []
- apiKey: []
servers:
- description: Local development server
  url: http://localhost:8000
- description: Production server
  url: http://api.dotmac.io:8000
tags:
- description: Health check endpoints
  name: Health
- description: API information endpoints
  name: API
