apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-portal
  namespace: dotmac
  labels:
    app: admin-portal
    tier: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: admin-portal
  template:
    metadata:
      labels:
        app: admin-portal
        tier: frontend
    spec:
      containers:
      - name: admin-portal
        image: dotmac/admin-portal:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"
        - name: HOSTNAME
          value: "0.0.0.0"
        - name: NEXT_PUBLIC_API_URL
          valueFrom:
            configMapKeyRef:
              name: frontend-config
              key: api_url
        - name: NEXT_PUBLIC_WEBSOCKET_URL
          valueFrom:
            configMapKeyRef:
              name: frontend-config
              key: websocket_url
        - name: NEXT_PUBLIC_APP_NAME
          value: "DotMac Admin Portal"
        - name: NEXT_PUBLIC_APP_DESCRIPTION
          value: "ISP Administration Portal"
        - name: NEXT_PUBLIC_OTEL_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: frontend-config
              key: otel_endpoint
              optional: true
        - name: NEXT_PUBLIC_SENTRY_DSN
          valueFrom:
            secretKeyRef:
              name: frontend-secrets
              key: sentry_dsn
              optional: true
        - name: SHUTDOWN_GRACE_PERIOD
          value: "30000"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 3
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/ready
            port: http
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "sleep 15"]
      terminationGracePeriodSeconds: 45
---
apiVersion: v1
kind: Service
metadata:
  name: admin-portal
  namespace: dotmac
  labels:
    app: admin-portal
    tier: frontend
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: admin-portal
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: admin-portal-hpa
  namespace: dotmac
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: admin-portal
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80