// Lighthouse CI configuration for admin
// Generated by create-lighthouse-config.js - DO NOT EDIT MANUALLY
// To regenerate, run: node scripts/create-lighthouse-config.js

const baseConfig = require('../../lighthouse.base.js');

module.exports = {
  ...baseConfig,
  ci: {
    ...baseConfig.ci,
    collect: {
      ...baseConfig.ci.collect,
      url: [
      "http://localhost:3000/",
      "http://localhost:3000/dashboard",
      "http://localhost:3000/billing",
      "http://localhost:3000/customers",
      "http://localhost:3000/network"
],
      startServerCommand: 'pnpm start',
      startServerReadyPattern: 'Ready on',
      startServerReadyTimeout: 60000
    },
    server: {
      ...baseConfig.ci.server,
      port: 12000
    }
  }
};
