apiVersion: v2
name: dotmac-isp-complete
description: Complete DotMac ISP Framework with integrated FreeRADIUS, Ansible, and VOLTHA
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - isp
  - radius
  - ansible
  - voltha
  - gpon
  - networking
home: https://dotmac.com
sources:
  - https://github.com/dotmac/dotmac-framework
maintainers:
  - name: DotMac Team
    email: support@dotmac.com
dependencies:
  - name: postgresql
    version: 13.2.24
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: 18.1.5
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: clickhouse
    version: 3.8.0
    repository: https://charts.bitnami.com/bitnami
    condition: clickhouse.enabled
  - name: openbao
    version: 0.25.0
    repository: https://openbao.github.io/openbao-helm
    condition: openbao.enabled
annotations:
  category: ISP Management
  licenses: Apache-2.0
