# Development Configuration for DotMac Framework
# Intelligent CI/CD Pipeline - Development Environment

environment: development
deployment_mode: intelligent_cicd_dev
framework_version: "1.0.0-dev"

# Domain and SSL Configuration (Development)
domain: localhost
ssl_enabled: false # Disabled for development
ssl_certificate_path: null
ssl_private_key_path: null

# Development-specific Pipeline Settings
intelligent_pipeline:
  test_success_threshold: 90.0 # Relaxed for development
  quality_gate_enforcement: lenient
  auto_deployment_enabled: true
  auto_remediation_enabled: true
  max_remediation_attempts: 5 # More attempts in dev
  deployment_timeout: 900 # 15 minutes
  rollback_timeout: 180 # 3 minutes

# Portal Applications Configuration (Development)
portals:
  frontend:
    admin:
      port: 3001
      path: frontend/apps/admin
      replicas: 1
      resources:
        cpu_limit: "500m"
        memory_limit: "512Mi"
        cpu_request: "100m"
        memory_request: "128Mi"
      environment_variables:
        NODE_ENV: development
        NEXT_PUBLIC_ENV: development
        NEXT_PUBLIC_API_URL: http://localhost:8000
        NEXT_PUBLIC_PORTAL_TYPE: admin
        NEXT_PUBLIC_DEBUG: true
      health_check:
        path: /api/health
        interval: 60 # Less frequent in dev
        timeout: 10
        retries: 2

    customer:
      port: 3002
      path: frontend/apps/customer
      replicas: 1
      resources:
        cpu_limit: "500m"
        memory_limit: "512Mi"
        cpu_request: "100m"
        memory_request: "128Mi"
      environment_variables:
        NODE_ENV: development
        NEXT_PUBLIC_ENV: development
        NEXT_PUBLIC_API_URL: http://localhost:8000
        NEXT_PUBLIC_PORTAL_TYPE: customer
        NEXT_PUBLIC_DEBUG: true
      health_check:
        path: /api/health
        interval: 60
        timeout: 10
        retries: 2

    reseller:
      port: 3003
      path: frontend/apps/reseller
      replicas: 1
      resources:
        cpu_limit: "500m"
        memory_limit: "512Mi"
        cpu_request: "100m"
        memory_request: "128Mi"
      environment_variables:
        NODE_ENV: development
        NEXT_PUBLIC_ENV: development
        NEXT_PUBLIC_API_URL: http://localhost:8000
        NEXT_PUBLIC_PORTAL_TYPE: reseller
        NEXT_PUBLIC_DEBUG: true
      health_check:
        path: /api/health
        interval: 60
        timeout: 10
        retries: 2

    technician:
      port: 3004
      path: frontend/apps/technician
      replicas: 1
      resources:
        cpu_limit: "400m"
        memory_limit: "384Mi"
        cpu_request: "100m"
        memory_request: "128Mi"
      environment_variables:
        NODE_ENV: development
        NEXT_PUBLIC_ENV: development
        NEXT_PUBLIC_API_URL: http://localhost:8000
        NEXT_PUBLIC_PORTAL_TYPE: technician
        NEXT_PUBLIC_OFFLINE_SUPPORT: true
        NEXT_PUBLIC_DEBUG: true
      health_check:
        path: /api/health
        interval: 60
        timeout: 10
        retries: 2

  backend:
    api_gateway:
      port: 8000
      service: dotmac_api_gateway
      replicas: 1
      resources:
        cpu_limit: "1000m"
        memory_limit: "1Gi"
        cpu_request: "200m"
        memory_request: "256Mi"
      environment_variables:
        ENVIRONMENT: development
        LOG_LEVEL: debug
        CORS_ORIGINS: "*" # Permissive in development
        RATE_LIMIT_REQUESTS_PER_MINUTE: 10000 # Very high limit for dev
        DEBUG: true
      health_check:
        path: /health
        interval: 60
        timeout: 10
        retries: 2

    identity:
      port: 8001
      service: dotmac_identity
      replicas: 1
      resources:
        cpu_limit: "500m"
        memory_limit: "512Mi"
        cpu_request: "100m"
        memory_request: "128Mi"
      environment_variables:
        ENVIRONMENT: development
        JWT_SECRET_KEY: dev-secret-key-not-for-production
        JWT_ACCESS_TOKEN_EXPIRE_MINUTES: 1440 # 24 hours in dev
        PASSWORD_RESET_TOKEN_EXPIRE_HOURS: 24
        DEBUG: true
      health_check:
        path: /health
        interval: 60
        timeout: 10
        retries: 2

    billing:
      port: 8002
      service: dotmac_billing
      replicas: 1
      resources:
        cpu_limit: "500m"
        memory_limit: "512Mi"
        cpu_request: "100m"
        memory_request: "128Mi"
      environment_variables:
        ENVIRONMENT: development
        PAYMENT_PROCESSOR_API_KEY: test-key-development
        STRIPE_WEBHOOK_SECRET: whsec_test_development
        DEBUG: true
      health_check:
        path: /health
        interval: 60
        timeout: 10
        retries: 2

# Load Balancer Configuration (Development)
load_balancer:
  type: nginx
  port: 80
  ssl_port: 443
  worker_processes: 1
  worker_connections: 256
  client_max_body_size: 10M
  proxy_read_timeout: 120 # Longer timeouts for debugging
  proxy_connect_timeout: 120
  proxy_send_timeout: 120

  backend_pools:
    api:
      servers:
        - localhost:8000
    frontend:
      admin:
        - localhost:3001
      customer:
        - localhost:3002
      reseller:
        - localhost:3003
      technician:
        - localhost:3004

  rate_limiting:
    enabled: false # Disabled in development

  security_headers:
    x_frame_options: SAMEORIGIN # More permissive
    x_content_type_options: nosniff
    x_xss_protection: "1; mode=block"
    # No HSTS in development
    content_security_policy: "default-src 'self' 'unsafe-inline' 'unsafe-eval'; img-src 'self' data: https:; connect-src 'self' ws: wss:;"

# Database Configuration (Development)
databases:
  primary:
    type: postgresql
    host: localhost
    port: 5432
    database: dotmac_dev
    username: dotmac_dev_user
    password: dev_password_123
    pool_size: 5
    max_overflow: 10
    pool_timeout: 30
    pool_recycle: 1800
    ssl_mode: disable # Disabled for development

  analytics:
    type: timescaledb
    host: localhost
    port: 5433
    database: dotmac_analytics_dev
    username: dotmac_analytics_dev
    password: dev_analytics_123
    pool_size: 3
    max_overflow: 5

  cache:
    type: redis
    host: localhost
    port: 6379
    password: null # No password in development
    database: 0
    max_connections: 10
    connection_pool_timeout: 20

# Monitoring and Observability (Development)
monitoring:
  enabled: true
  metrics_collection_interval: 30 # Less frequent
  log_level: debug
  log_rotation:
    max_size: 50MB
    max_files: 5
    compress: false # No compression in dev

  # Monitoring is provided by SigNoz (OTLP)

  alerting:
    enabled: false # Disabled in development

  apm:
    enabled: false # Disabled to reduce overhead

  logging:
    centralized: false # Local logging only
    log_retention_days: 7

# Security Configuration (Development - Relaxed)
security:
  jwt:
    secret_key: dev-jwt-secret-not-for-production-use-only
    algorithm: HS256
    access_token_expire_minutes: 1440 # 24 hours for dev convenience
    refresh_token_expire_days: 7

  encryption:
    fernet_key: dev-fernet-key-not-for-production

  cors:
    enabled: true
    allowed_origins: ["*"] # Permissive in development
    allow_credentials: true
    allowed_methods: ["*"]
    allowed_headers: ["*"]

  rate_limiting:
    enabled: false # Disabled for development

  api_security:
    require_https: false
    api_key_header: X-API-Key
    request_id_header: X-Request-ID

  csp:
    enabled: false # Disabled for easier development

# Performance Configuration (Development)
performance:
  caching:
    enabled: true
    default_ttl: 60 # Shorter TTL for development
    redis_url: redis://localhost:6379/1

  database_pooling:
    enabled: true
    pool_size: 5
    max_overflow: 10
    pool_timeout: 30

  assets:
    compression: none # No compression for faster builds
    caching_headers: false
    cdn_enabled: false

  # Relaxed thresholds for development
  thresholds:
    response_time_p95: 2000 # ms
    response_time_p99: 5000 # ms
    memory_usage_warning: 85 # %
    memory_usage_critical: 95 # %
    cpu_usage_warning: 85 # %
    cpu_usage_critical: 95 # %
    disk_usage_warning: 90 # %
    disk_usage_critical: 98 # %

# Resource Limits and Scaling (Development)
scaling:
  auto_scaling:
    enabled: false # Disabled in development

  resource_requests:
    cpu: 100m
    memory: 128Mi

  resource_limits:
    cpu: 1000m
    memory: 1Gi

  hpa:
    enabled: false # Disabled in development

# Backup and Disaster Recovery (Development)
backup:
  enabled: false # Disabled for development

# Networking (Development)
networking:
  service_mesh:
    enabled: false

  ingress:
    enabled: false # Direct access in development

  service_discovery:
    enabled: false # Direct IP/port access

  network_policies:
    enabled: false # Open network in development

# Development-specific Features
development:
  hot_reload: true
  debug_mode: true
  profiling: true
  source_maps: true
  verbose_logging: true

  # Development tools
  tools:
    swagger_ui: true
    api_docs: true
    debug_toolbar: true
    query_profiler: true

  # Test data
  seed_data:
    enabled: true
    reset_on_startup: false
    include_test_users: true

  # Development servers
  dev_servers:
    webpack_dev_server: true
    hot_module_replacement: true
    live_reload: true

# Feature Flags (Development)
features:
  intelligent_deployment: true
  auto_remediation: true
  performance_monitoring: false # Disabled to reduce overhead
  security_monitoring: false # Disabled in development
  user_analytics: false # Disabled in development
  a11y_monitoring: true
  real_time_alerts: false
  deployment_rollback: true
  canary_deployments: false
  blue_green_deployments: false

# Maintenance (Development)
maintenance:
  maintenance_mode: false
  maintenance_message: "Development environment is temporarily unavailable."
  allowed_ips: []

  windows: [] # No scheduled maintenance in development

# Development Environment Variables
environment_variables:
  NODE_ENV: development
  ENVIRONMENT: development
  DEBUG: true
  LOG_LEVEL: debug
  CORS_ENABLED: true
  RATE_LIMITING_ENABLED: false
  SSL_ENABLED: false

# Docker Compose Overrides for Development
docker_compose:
  services:
    postgres:
      ports:
        - "5432:5432"
      environment:
        POSTGRES_DB: dotmac_dev
        POSTGRES_USER: dotmac_dev_user
        POSTGRES_PASSWORD: dev_password_123

    redis:
      ports:
        - "6379:6379"
      command: redis-server --appendonly yes

    timescaledb:
      ports:
        - "5433:5432"
      environment:
        POSTGRES_DB: dotmac_analytics_dev
        POSTGRES_USER: dotmac_analytics_dev
        POSTGRES_PASSWORD: dev_analytics_123

# Testing Configuration (Development)
testing:
  unit_tests:
    coverage_threshold: 80
    parallel_execution: true

  integration_tests:
    timeout: 300 # 5 minutes
    retry_attempts: 2

  e2e_tests:
    timeout: 600 # 10 minutes
    browsers: ["chromium"] # Only one browser in dev
    parallel: false

  performance_tests:
    enabled: false # Disabled by default in dev

  accessibility_tests:
    enabled: true
    standards: ["WCAG2AA"]

# Local Development Ports
dev_ports:
  frontend_admin: 3001
  frontend_customer: 3002
  frontend_reseller: 3003
  frontend_technician: 3004
  api_gateway: 8000
  identity_service: 8001
  billing_service: 8002
  services_service: 8003
  networking_service: 8004
  analytics_service: 8005
  platform_service: 8006
  prometheus: 9090
  grafana: 3000
  alertmanager: 9093
  node_exporter: 9100
  blackbox_exporter: 9115
