// Lighthouse CI configuration for technician
// Generated by create-lighthouse-config.js - DO NOT EDIT MANUALLY
// To regenerate, run: node scripts/create-lighthouse-config.js

const baseConfig = require('../../lighthouse.base.js');

module.exports = {
  ...baseConfig,
  ci: {
    ...baseConfig.ci,
    collect: {
      ...baseConfig.ci.collect,
      url: [
      "http://localhost:3005/",
      "http://localhost:3005/dashboard",
      "http://localhost:3005/jobs",
      "http://localhost:3005/inventory",
      "http://localhost:3005/diagnostics"
],
      startServerCommand: 'pnpm start',
      startServerReadyPattern: 'Ready on',
      startServerReadyTimeout: 60000
    },
    server: {
      ...baseConfig.ci.server,
      port: 12005
    }
  }
};
