[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "dotmac-business-logic"
version = "1.0.0"
description = "Business logic components for DotMac framework - tasks, billing, and file management"
readme = "README.md"
authors = [
    {name = "DotMac Framework Team", email = "support@dotmac.dev"}
]
license = {text = "MIT"}
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Office/Business",
    "Topic :: Internet :: WWW/HTTP :: Dynamic Content",
    "Topic :: Software Development :: Libraries :: Python Modules"
]
keywords = ["business-logic", "tasks", "billing", "files", "workflow", "background-processing"]
requires-python = ">=3.9,<4"
dependencies = [
    # Core dependencies
    "sqlalchemy>=2.0.0",
    "pydantic>=2.0.0",
    "pydantic-settings>=2.0.0",
    "fastapi>=0.100.0",
    "alembic>=1.12.0",
    "python-dateutil>=2.8.0",
    "typing-extensions>=4.0.0",
    "structlog>=23.1.0",
    # Task processing
    "celery>=5.3.0",
    "redis>=4.5.0",
    # File processing
    "aiofiles>=23.0.0",
    "jinja2>=3.1.0",
]

[project.optional-dependencies]
# Database backends
postgresql = ["asyncpg>=0.28.0"]
mysql = ["aiomysql>=0.2.0"]

# Payment processors for billing
stripe = ["stripe>=5.5.0"]
paypal = ["paypalrestsdk>=1.13.0"]

# Document generation
pdf = ["reportlab>=4.0.0", "weasyprint>=59.0"]
excel = ["openpyxl>=3.1.0"]

# Message queues
rabbitmq = ["kombu>=5.3.0"]
kafka = ["kafka-python>=2.0.0"]

# All features
all = [
    "asyncpg>=0.28.0",
    "redis>=4.5.0", 
    "stripe>=5.5.0",
    "reportlab>=4.0.0",
    "openpyxl>=3.1.0",
    "kombu>=5.3.0"
]

# Development dependencies
dev = [
    "pytest>=7.0.0",
    "pytest-asyncio>=0.21.0",
    "pytest-cov>=4.1.0",
    "pytest-mock>=3.11.0",
    "black>=23.0.0",
    "ruff>=0.1.0",
    "mypy>=1.5.0"
]

[project.urls]
Homepage = "https://github.com/dotmac-framework/dotmac-business-logic"
Documentation = "https://docs.dotmac.dev/business-logic"
Repository = "https://github.com/dotmac-framework/dotmac-business-logic"
Issues = "https://github.com/dotmac-framework/dotmac-business-logic/issues"

[tool.setuptools.packages.find]
where = ["src"]
include = ["dotmac_business_logic*"]

[tool.setuptools.package-data]
"dotmac_business_logic" = ["templates/*.html", "migrations/*.sql", "config/*.yaml"]

[tool.black]
line-length = 100
target-version = ['py39', 'py310', 'py311', 'py312']
include = '\.pyi?$'
extend-exclude = '''
/(
  \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | migrations
)/
'''

[tool.ruff]
target-version = "py39"
select = ["E", "W", "F", "I", "N", "UP", "B", "C4", "S", "T20"]
ignore = ["E501", "S101", "S104", "S108"]
src = ["src", "tests"]

[tool.mypy]
python_version = "3.9"
strict = true
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true

[[tool.mypy.overrides]]
module = ["stripe.*", "paypalrestsdk.*", "reportlab.*", "weasyprint.*", "celery.*"]
ignore_missing_imports = true

[tool.pytest.ini_options]
minversion = "7.0"
addopts = "-ra -q --cov=dotmac_business_logic --cov-report=term-missing"
testpaths = ["tests"]
asyncio_mode = "auto"
markers = [
    "unit: Unit tests",
    "integration: Integration tests",
    "slow: Tests that take longer than 1 second"
]