# Test Communication Plugin Configuration
# This file is for testing plugin system functionality

plugin_paths:
  - "plugins/communication"

enabled_plugins:
  # Test Channel Plugin (no external dependencies)
  - plugin_id: "test_channel"
    enabled: true
    priority: 1
    config:
      test_mode: true

# Plugin system settings
settings:
  auto_reload: false
  security_validation: false  # Disabled for testing
  max_concurrent_sends: 10
  circuit_breaker_enabled: false
  health_check_interval: 60