# ISP Framework Communication Plugin Configuration
# Strategic plugin system configuration for ISP Framework modules

plugin_paths:
  - "../../plugins/communication" # Shared plugins
  - "plugins/communication" # ISP-specific plugins
  - "/opt/dotmac/isp/plugins/communication" # System-wide ISP plugins

enabled_plugins:
  # SMS Communication
  - plugin_id: "twilio_sms"
    enabled: true
    priority: 1
    config:
      account_sid: "${ISP_TWILIO_SID}"
      auth_token: "${ISP_TWILIO_TOKEN}"
      from_number: "${ISP_TWILIO_FROM_NUMBER}"
      webhook_url: "${ISP_BASE_URL}/webhooks/sms"
      max_retries: 3
      timeout_seconds: 30

  # Email Communication
  - plugin_id: "sendgrid_email"
    enabled: true
    priority: 1
    config:
      api_key: "${ISP_SENDGRID_API_KEY}"
      from_email: "${ISP_FROM_EMAIL}"
      from_name: "ISP Customer Support"
      template_id: "${ISP_SENDGRID_TEMPLATE_ID}"

  # Alternative SMS Provider (failover)
  - plugin_id: "vonage_sms"
    enabled: false # Enable as backup
    priority: 2
    config:
      api_key: "${ISP_VONAGE_API_KEY}"
      api_secret: "${ISP_VONAGE_API_SECRET}"
      from_number: "${ISP_VONAGE_FROM_NUMBER}"

  # SMTP Email (fallback)
  - plugin_id: "smtp_email"
    enabled: true
    priority: 2 # Lower priority (fallback)
    config:
      smtp_server: "${ISP_SMTP_SERVER}"
      smtp_port: "${ISP_SMTP_PORT}"
      username: "${ISP_SMTP_USERNAME}"
      password: "${ISP_SMTP_PASSWORD}"
      use_tls: true
      from_email: "${ISP_FROM_EMAIL}"
      from_name: "ISP Customer Support"

  # Slack Integration (for internal alerts)
  - plugin_id: "slack_webhook"
    enabled: true
    priority: 1
    config:
      webhook_url: "${ISP_SLACK_WEBHOOK_URL}"
      default_channel: "#isp-alerts"
      username: "ISP Monitor"
      icon_emoji: ":warning:"

  # Teams Integration (for internal notifications)
  - plugin_id: "teams_webhook"
    enabled: false
    priority: 2
    config:
      webhook_url: "${ISP_TEAMS_WEBHOOK_URL}"

  # Generic Webhook (for custom integrations)
  - plugin_id: "generic_webhook"
    enabled: true
    priority: 3 # Lowest priority
    config:
      timeout_seconds: 30
      retry_attempts: 3
      verify_ssl: true

# ISP-specific plugin system settings
settings:
  auto_reload: true
  security_validation: true
  max_concurrent_sends: 50 # Adjust based on ISP capacity
  circuit_breaker_enabled: true
  health_check_interval: 300 # 5 minutes
  enable_delivery_receipts: true
  enable_webhook_processing: true

# ISP Framework environment defaults
defaults:
  timeout_seconds: 30
  max_retries: 3
  rate_limit_per_minute: 100 # Conservative for ISP use
  enable_logging: true
  log_level: "INFO"

# Channel routing preferences (ISP-specific)
channel_preferences:
  # Customer notifications
  customer_notifications:
    preferred_channels: ["email", "sms"]
    fallback_channels: ["email"] # Always fallback to email

  # Service alerts
  service_alerts:
    preferred_channels: ["sms", "email"]
    urgent_channels: ["sms"] # SMS for urgent alerts

  # Billing notifications
  billing_notifications:
    preferred_channels: ["email"]
    reminder_channels: ["sms", "email"]

  # Internal alerts
  internal_alerts:
    preferred_channels: ["slack", "teams"]
    critical_channels: ["sms"] # SMS for critical internal alerts

# ISP Framework integration settings
isp_framework:
  customer_service_integration: true
  billing_integration: true
  service_monitoring_integration: true
  template_system_integration: true
  audit_logging: true
