receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  jaeger:
    protocols:
      grpc:
        endpoint: 0.0.0.0:14250

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024
  memory_limiter:
    limit_mib: 512

exporters:
  clickhousetraces:
    endpoint: tcp://clickhouse:9000?database=signoz_traces
    username: default
    password: ""
    timeout: 5s
  clickhousemetricswrite:
    endpoint: tcp://clickhouse:9000?database=signoz_metrics
    username: default
    password: ""
    timeout: 5s
  clickhouselogsexporter:
    endpoint: tcp://clickhouse:9000?database=signoz_logs
    username: default
    password: ""
    timeout: 5s

service:
  pipelines:
    traces:
      receivers: [otlp, jaeger]
      processors: [memory_limiter, batch]
      exporters: [clickhousetraces]
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [clickhousemetricswrite]
    logs:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [clickhouselogsexporter]