#!/bin/bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
COMPOSE_FILE="$SCRIPT_DIR/docker-compose.infra.yml"
ENV_OUT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)/gate-e"
ENV_FILE="$ENV_OUT_DIR/.env.gate-e"

mkdir -p "$ENV_OUT_DIR"

POSTGRES_USER="${POSTGRES_USER:-dotmac_admin}"
POSTGRES_PASSWORD="${POSTGRES_PASSWORD:-password123}"
POSTGRES_DB="${POSTGRES_DB:-dotmac_test}"
REDIS_PASSWORD="${REDIS_PASSWORD:-redis123}"

echo "[infra] Starting shared infra (Postgres, Redis)..."
docker compose -f "$COMPOSE_FILE" up -d --build

echo "[infra] Waiting for health..."
# Wait for Postgres
timeout 120 bash -c 'until pg_isready -h localhost -p 5440 -U dotmac_admin >/dev/null 2>&1; do sleep 2; done'
# Wait for Redis
timeout 120 bash -c 'until redis-cli -p 6390 -a "'"$REDIS_PASSWORD"'" ping >/dev/null 2>&1; do sleep 2; done'

DB_URL="postgresql+asyncpg://$POSTGRES_USER:$POSTGRES_PASSWORD@localhost:5440/$POSTGRES_DB"
REDIS_URL="redis://:$REDIS_PASSWORD@localhost:6390/0"

cat > "$ENV_FILE" <<EOF
# Generated by Gate E Infra
DATABASE_URL=$DB_URL
REDIS_URL=$REDIS_URL
POSTGRES_HOST=localhost
POSTGRES_PORT=5440
POSTGRES_USER=$POSTGRES_USER
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
POSTGRES_DB=$POSTGRES_DB
REDIS_HOST=localhost
REDIS_PORT=6390
REDIS_PASSWORD=$REDIS_PASSWORD
EOF

echo "[infra] Shared env written to $ENV_FILE"
echo "DATABASE_URL=$DB_URL"
echo "REDIS_URL=$REDIS_URL"

