// Lighthouse CI configuration for management-admin
// Generated by create-lighthouse-config.js - DO NOT EDIT MANUALLY
// To regenerate, run: node scripts/create-lighthouse-config.js

const baseConfig = require('../../lighthouse.base.js');

module.exports = {
  ...baseConfig,
  ci: {
    ...baseConfig.ci,
    collect: {
      ...baseConfig.ci.collect,
      url: [
        'http://localhost:3003/',
        'http://localhost:3003/dashboard',
        'http://localhost:3003/tenants',
        'http://localhost:3003/plugins',
        'http://localhost:3003/system',
      ],
      startServerCommand: 'pnpm start',
      startServerReadyPattern: 'Ready on',
      startServerReadyTimeout: 60000,
    },
    server: {
      ...baseConfig.ci.server,
      port: 12003,
    },
  },
};
