# Codecov configuration for Customer App
coverage:
  status:
    project:
      default:
        target: 90%
        threshold: 1%
        if_not_found: success
        if_ci_failed: error
    patch:
      default:
        target: 85%
        threshold: 1%
        if_not_found: success
        if_ci_failed: error

  ignore:
    - "**/*.d.ts"
    - "**/*.test.*"
    - "**/__tests__/**"
    - "**/__mocks__/**"
    - "**/coverage/**"
    - "**/.next/**"
    - "**/dist/**"
    - "**/node_modules/**"
    - "**/*.config.js"
    - "**/*.config.ts"
    - "**/jest-setup.js"

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no

flags:
  unit:
    paths:
      - src/
  integration:
    paths:
      - src/
  customer-app:
    paths:
      - apps/customer/src/