apiVersion: v1
kind: Secret
metadata:
  name: dotmac-isp-secrets
  namespace: dotmac-isp-framework
  labels:
    app.kubernetes.io/name: dotmac-isp-framework
    app.kubernetes.io/component: secrets
type: Opaque
stringData:
  # Database credentials (base64 encoded in production)
  DATABASE_URL: "postgresql://user:password@postgresql:5432/dotmac_isp"
  
  # Redis credentials
  REDIS_URL: "redis://redis:6379/0"
  
  # JWT secrets
  JWT_SECRET_KEY: "change-me-in-production"
  JWT_ALGORITHM: "HS256"
  JWT_EXPIRATION_HOURS: "24"
  
  # External service credentials
  SMTP_PASSWORD: "change-me"
  S3_ACCESS_KEY: "change-me"
  S3_SECRET_KEY: "change-me"
  
  # API keys for integrations
  BILLING_API_KEY: "change-me"
  MONITORING_API_KEY: "change-me"
  
  # Encryption keys
  FIELD_ENCRYPTION_KEY: "change-me-32-char-key-for-encryption"
  
---
# Template for tenant-specific secrets
apiVersion: v1
kind: Secret
metadata:
  name: tenant-template-secrets
  namespace: dotmac-tenants
  labels:
    app.kubernetes.io/name: dotmac-tenant
    app.kubernetes.io/component: secrets
    dotmac.io/tenant-template: "true"
type: Opaque
stringData:
  # Tenant-specific database
  DATABASE_URL: "postgresql://tenant_user:tenant_password@postgresql:5432/tenant_db"
  
  # Tenant-specific Redis namespace
  REDIS_URL: "redis://redis:6379/1"
  
  # Tenant-specific JWT secret (generated per tenant)
  JWT_SECRET_KEY: "tenant-specific-jwt-secret"
  
  # Tenant-specific API keys
  TENANT_API_KEY: "tenant-specific-api-key"
  
  # License validation
  LICENSE_VALIDATION_KEY: "tenant-license-validation-key"