apiVersion: v1
kind: Service
metadata:
  name: dotmac-isp-framework
  namespace: dotmac-isp-framework
  labels:
    app.kubernetes.io/name: dotmac-isp-framework
    app.kubernetes.io/component: application
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  - name: metrics
    port: 9090
    targetPort: metrics
    protocol: TCP
  selector:
    app.kubernetes.io/name: dotmac-isp-framework
    app.kubernetes.io/component: application

---
# Headless service for StatefulSet deployments (tenant-specific)
apiVersion: v1
kind: Service
metadata:
  name: dotmac-isp-framework-headless
  namespace: dotmac-isp-framework
  labels:
    app.kubernetes.io/name: dotmac-isp-framework
    app.kubernetes.io/component: application
spec:
  clusterIP: None
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  selector:
    app.kubernetes.io/name: dotmac-isp-framework
    app.kubernetes.io/component: application

---
# External LoadBalancer service for production ingress
apiVersion: v1
kind: Service
metadata:
  name: dotmac-isp-framework-external
  namespace: dotmac-isp-framework
  labels:
    app.kubernetes.io/name: dotmac-isp-framework
    app.kubernetes.io/component: external-lb
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:us-west-2:123456789012:certificate/12345678-1234-1234-1234-123456789012"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
spec:
  type: LoadBalancer
  ports:
  - name: https
    port: 443
    targetPort: http
    protocol: TCP
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  selector:
    app.kubernetes.io/name: dotmac-isp-framework
    app.kubernetes.io/component: application
  loadBalancerSourceRanges:
  - 0.0.0.0/0  # Configure this for production security