extensions:
  health_check: {}
  zpages: {}

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  prometheus:
    config:
      scrape_configs:
        - job_name: "otel-collector"
          scrape_interval: 10s
          static_configs:
            - targets: ["0.0.0.0:8889"]

processors:
  batch: {}
  memory_limiter:
    limit_mib: 512
  resource:
    attributes:
      - key: service.name
        value: dotmac-platform
        action: upsert

exporters:
  clickhousetraces:
    datasource: tcp://${CLICKHOUSE_HOST}:9000/?database=signoz_traces&username=signoz&password=${CLICKHOUSE_PASSWORD}
  clickhousemetricswrite:
    dsn: tcp://${CLICKHOUSE_HOST}:9000/?database=signoz_metrics&username=signoz&password=${CLICKHOUSE_PASSWORD}
  clickhouselogsexporter:
    dsn: tcp://${CLICKHOUSE_HOST}:9000/?database=signoz_logs&username=signoz&password=${CLICKHOUSE_PASSWORD}
  logging:
    loglevel: debug

service:
  extensions: [health_check, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch, resource]
      exporters: [clickhousetraces]
    metrics:
      receivers: [otlp, prometheus]
      processors: [memory_limiter, batch, resource]
      exporters: [clickhousemetricswrite]
    logs:
      receivers: [otlp]
      processors: [memory_limiter, batch, resource]
      exporters: [clickhouselogsexporter, logging]
