// Lighthouse CI configuration for tenant-portal
// Generated by create-lighthouse-config.js - DO NOT EDIT MANUALLY
// To regenerate, run: node scripts/create-lighthouse-config.js

const baseConfig = require('../../lighthouse.base.js');

module.exports = {
  ...baseConfig,
  ci: {
    ...baseConfig.ci,
    collect: {
      ...baseConfig.ci.collect,
      url: [
      "http://localhost:3006/",
      "http://localhost:3006/dashboard",
      "http://localhost:3006/configuration",
      "http://localhost:3006/monitoring"
],
      startServerCommand: 'pnpm start',
      startServerReadyPattern: 'Ready on',
      startServerReadyTimeout: 60000
    },
    server: {
      ...baseConfig.ci.server,
      port: 12006
    }
  }
};
