apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotmac-management
  namespace: dotmac-system
  labels:
    app.kubernetes.io/name: dotmac-management
    app.kubernetes.io/instance: dotmac-platform
    app.kubernetes.io/component: management-api
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: kubectl
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: dotmac-management
      app.kubernetes.io/instance: dotmac-platform
  template:
    metadata:
      labels:
        app.kubernetes.io/name: dotmac-management
        app.kubernetes.io/instance: dotmac-platform
        app.kubernetes.io/component: management-api
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: dotmac-management
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - name: management-api
        image: dotmac/management:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8000
          protocol: TCP
        env:
        - name: DOTMAC_ENVIRONMENT
          value: "production"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: dotmac-secrets
              key: database-url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: dotmac-secrets
              key: redis-url
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: dotmac-secrets
              key: secret-key
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: dotmac-secrets
              key: jwt-secret
        - name: PLUGIN_REGISTRY_PATH
          value: "/app/plugins"
        - name: PLUGIN_DATA_PATH
          value: "/app/data"
        - name: PLUGIN_LOGS_PATH
          value: "/app/logs"
        - name: INIT_PLUGIN_REGISTRY
          value: "true"
        - name: ENABLE_MONITORING
          value: "true"
        volumeMounts:
        - name: plugin-registry
          mountPath: /app/plugins
        - name: plugin-data
          mountPath: /app/data
        - name: plugin-logs
          mountPath: /app/logs
        - name: config-volume
          mountPath: /app/config
          readOnly: true
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/health
            port: http
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /api/health
            port: http
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 30
      volumes:
      - name: plugin-registry
        persistentVolumeClaim:
          claimName: plugin-registry-pvc
      - name: plugin-data
        persistentVolumeClaim:
          claimName: plugin-data-pvc
      - name: plugin-logs
        persistentVolumeClaim:
          claimName: plugin-logs-pvc
      - name: config-volume
        configMap:
          name: dotmac-config
      tolerations:
      - key: node.kubernetes.io/not-ready
        operator: Exists
        effect: NoExecute
        tolerationSeconds: 30
      - key: node.kubernetes.io/unreachable
        operator: Exists
        effect: NoExecute
        tolerationSeconds: 30
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                  - dotmac-management
              topologyKey: kubernetes.io/hostname