"""Core SDK utilities and base classes for ISP Framework."""

from .client import BaseSDKClient, sdk_method, sdk_retry
from .exceptions import (
    SDKError,
    SDKConnectionError,
    SDKAuthenticationError,
    SDKValidationError,
    SDKRateLimitError,
    SDKTimeoutError,
    SDKNotFoundError,
    SDKConfigurationError,
    SDKServiceUnavailableError,
    CustomerError,
    IPAMError,
    IPAddressConflictError,
    ServiceDefinitionError,
    ServicePlanError,
    TenantError,
    handle_sdk_error,
    is_retryable_error,
)
from .utils import (
    build_headers,
    parse_response,
    validate_uuid,
    validate_email,
    validate_phone,
    sanitize_string,
    paginate_list,
    generate_request_id,
    format_datetime,
    parse_datetime,
    build_query_params,
    deep_merge_dicts,
    mask_sensitive_data,
    RequestContext,
)

__all__ = [
    # Base client
    "BaseSDKClient",
    "sdk_method",
    "sdk_retry",
    
    # Exceptions
    "SDKError",
    "SDKConnectionError",
    "SDKAuthenticationError", 
    "SDKValidationError",
    "SDKRateLimitError",
    "SDKTimeoutError",
    "SDKNotFoundError",
    "SDKConfigurationError",
    "SDKServiceUnavailableError",
    "CustomerError",
    "IPAMError",
    "IPAddressConflictError",
    "ServiceDefinitionError",
    "ServicePlanError",
    "TenantError",
    "handle_sdk_error",
    "is_retryable_error",
    
    # Utilities
    "build_headers",
    "parse_response",
    "validate_uuid",
    "validate_email",
    "validate_phone",
    "sanitize_string", 
    "paginate_list",
    "generate_request_id",
    "format_datetime",
    "parse_datetime",
    "build_query_params",
    "deep_merge_dicts",
    "mask_sensitive_data",
    "RequestContext",
]