name: Extended E2E

on:
  workflow_dispatch:
  push:
    branches: [ main, develop ]

jobs:
  e2e-services-and-frontend:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Playwright browsers
        working-directory: frontend
        run: |
          npm -v
          npx playwright install --with-deps

      - name: Start Notification Test Stack
        run: |
          docker compose -f docker/test-services/docker-compose.test-notifications.yml up -d --build

      - name: Wait for Notification Services
        run: |
          timeout 120 bash -c 'until curl -sf http://localhost:8025/; do sleep 2; done'
          timeout 120 bash -c 'until curl -sf http://localhost:3030/health; do sleep 2; done'
          timeout 120 bash -c 'until curl -sf http://localhost:8080/health; do sleep 2; done'

      - name: Start File Storage Test Stack
        run: |
          docker compose -f docker/test-services/docker-compose.test-filestorage.yml up -d --build

      - name: Wait for File Storage Services
        run: |
          timeout 180 bash -c 'until curl -sf http://localhost:9000/minio/health/live; do sleep 3; done'
          timeout 180 bash -c 'until curl -sf http://localhost:8081/health; do sleep 3; done'

      - name: Run Notification Tester
        run: |
          curl -sf -X POST http://localhost:8080/run-tests
          sleep 2
          curl -sf http://localhost:8080/results | tee notification-results.json

      - name: Run File Storage Tester
        run: |
          curl -sf -X POST http://localhost:8081/run-tests
          sleep 2
          curl -sf http://localhost:8081/results | tee filestorage-results.json

      - name: Run Mocked SSO Playwright Suite
        working-directory: frontend
        run: |
          npx playwright test -c tests/sso-playwright.config.ts --reporter=list

      - name: Run Payments Edge Cases Suite
        working-directory: frontend
        run: |
          npx playwright test -c tests/payments-playwright.config.ts --reporter=list

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.lock || pip install -r requirements.txt

      - name: Run Python E2E tests
        env:
          PYTHONPATH: src
        run: |
          python -m pytest -m "e2e" -v --tb=short

      - name: Tear down services
        if: always()
        run: |
          docker compose -f docker/test-services/docker-compose.test-filestorage.yml down -v
          docker compose -f docker/test-services/docker-compose.test-notifications.yml down -v
