name: Main CI Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

permissions:
  contents: read
  pull-requests: read
  checks: write
  statuses: write

env:
  PYTHON_VERSION: '3.11'
  NODE_VERSION: '18'
  PNPM_VERSION: '8'

jobs:
  # Change detection for efficient builds
  detect-changes:
    name: Detect Changes
    runs-on: ubuntu-latest
    outputs:
      frontend: ${{ steps.changes.outputs.frontend }}
      backend: ${{ steps.changes.outputs.backend }}
      shared: ${{ steps.changes.outputs.shared }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            frontend:
              - 'frontend/**'
            backend:
              - 'src/**'
              - 'packages/**'
              - 'tests/**'
            shared:
              - 'pyproject.toml'
              - 'requirements*.txt'
              - '.github/workflows/**'
              - 'poetry.lock'

  # Security scanning (always runs)
  security:
    name: Security Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: latest
          virtualenvs-create: true
          virtualenvs-in-project: true
          
      - name: Cache Poetry dependencies
        uses: actions/cache@v4
        with:
          path: .venv
          key: poetry-security-${{ runner.os }}-${{ env.PYTHON_VERSION }}-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            poetry-security-${{ runner.os }}-${{ env.PYTHON_VERSION }}-
      
      - name: Install dependencies
        run: |
          poetry install --with security
      
      - name: Security checks
        run: |
          poetry run bandit -r src/ -f json -o bandit-report.json || true
          poetry run safety scan --output json > safety-report.json || true
      
      - name: Upload security reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: security-reports
          path: |
            bandit-report.json
            safety-report.json
          retention-days: 30
      
      - name: Secret scanning
        run: |
          echo "🔍 Scanning for hardcoded secrets (excluding tests)..."
          
          # Use Python script for reliable secret scanning
          python3 << 'EOF'
          import os
          import re
          import sys
          
          def find_production_files():
              production_files = []
              for root, dirs, files in os.walk('.'):
                  # Skip test directories and common non-production paths
                  dirs[:] = [d for d in dirs if not any(skip in d for skip in [
                      'test', '__test', '.git', 'node_modules', '__pycache__', 
                      'examples', 'mock', '.dev-artifacts'
                  ])]
                  
                  for file in files:
                      if file.endswith(('.py', '.js', '.ts', '.jsx', '.tsx')) and not any(skip in file for skip in ['test.', 'spec.']):
                          production_files.append(os.path.join(root, file))
              
              return production_files
          
          def scan_file(file_path):
              try:
                  with open(file_path, 'r', encoding='utf-8', errors='ignore') as f:
                      content = f.read()
                  
                  # Check for API keys
                  api_key_pattern = re.compile(r'sk_[a-zA-Z0-9_]{32,}|pk_[a-zA-Z0-9_]{32,}|rk_[a-zA-Z0-9_]{32,}')
                  if api_key_pattern.search(content):
                      print(f"❌ Potential API key found in: {file_path}")
                      return True
                  
                  # Check for hardcoded credentials
                  credential_pattern = re.compile(r'(password|secret|key|token)\s*[:=]\s*["\'][a-zA-Z0-9]{12,}["\']', re.IGNORECASE)
                  matches = credential_pattern.search(content)
                  if matches:
                      # Exclude known safe patterns
                      safe_patterns = ['CHANGE_ME', 'INSECURE', 'EXAMPLE', 'template', 'config', 'test-', 'demo-', 'placeholder']
                      is_safe = any(safe in content for safe in safe_patterns)
                      
                      if not is_safe:
                          print(f"❌ Potential hardcoded credential found in: {file_path}")
                          return True
                  
              except Exception as e:
                  print(f"Warning: Could not scan {file_path}: {e}")
              
              return False
          
          files = find_production_files()
          print(f"Scanning {len(files)} production files...")
          
          issues_found = False
          for file_path in files:
              if scan_file(file_path):
                  issues_found = True
          
          if issues_found:
              print("❌ Security issues detected!")
              sys.exit(1)
          else:
              print("✅ No hardcoded secrets detected in production code")
          EOF
      
      - name: Security Bootstrap Validation
        env:
          AUTH_ADMIN_EMAIL: "${{ secrets.AUTH_ADMIN_EMAIL }}"
          AUTH_INITIAL_ADMIN_PASSWORD: "${{ secrets.AUTH_INITIAL_ADMIN_PASSWORD }}"
        run: |
          if [ -z "${AUTH_ADMIN_EMAIL:-}" ] || [ -z "${AUTH_INITIAL_ADMIN_PASSWORD:-}" ]; then
            echo "⚠️ Skipping bootstrap validation: secrets not configured"
            exit 0
          fi
          
          # Basic validation of environment variables for security bootstrap
          echo "🔐 Validating security bootstrap environment..."
          
          # Check email format
          if [[ ! "${AUTH_ADMIN_EMAIL}" =~ ^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$ ]]; then
            echo "❌ Invalid email format for AUTH_ADMIN_EMAIL"
            exit 1
          fi
          
          # Check password strength (basic)
          if [[ ${#AUTH_INITIAL_ADMIN_PASSWORD} -lt 12 ]]; then
            echo "❌ AUTH_INITIAL_ADMIN_PASSWORD too short (minimum 12 characters)"
            exit 1
          fi
          
          echo "✅ Security bootstrap environment validated"

  # Frontend lint + typecheck (monorepo)
  frontend-lint:
    name: Frontend Lint and Typecheck
    runs-on: ubuntu-latest
    needs: [detect-changes, security]
    if: needs.detect-changes.outputs.frontend == 'true' || needs.detect-changes.outputs.shared == 'true'
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'
          cache-dependency-path: frontend/pnpm-lock.yaml

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Install frontend dependencies
        run: pnpm -C frontend install --frozen-lockfile

      - name: Lint (ESLint)
        run: pnpm -C frontend -r run lint

      - name: Typecheck (TypeScript)
        run: pnpm -C frontend -r run typecheck || pnpm -C frontend -r run type-check || pnpm -C frontend -r run ts:check

  # Backend testing
  backend:
    name: Backend Tests
    runs-on: ubuntu-latest
    needs: [detect-changes, security]
    if: needs.detect-changes.outputs.backend == 'true' || needs.detect-changes.outputs.shared == 'true'
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: test_password
          POSTGRES_USER: test_user
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      
      redis:
        image: redis:7
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: latest
          virtualenvs-create: true
          virtualenvs-in-project: true
          
      - name: Cache Poetry dependencies
        uses: actions/cache@v4
        with:
          path: .venv
          key: poetry-backend-${{ runner.os }}-${{ env.PYTHON_VERSION }}-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            poetry-backend-${{ runner.os }}-${{ env.PYTHON_VERSION }}-
      
      - name: Install dependencies
        run: |
          poetry install
      
      - name: Lint and type check
        run: |
          poetry run ruff check src/
          poetry run black --check src/
          poetry run mypy src/ || true  # Non-blocking for now
      
      - name: Run tests
        run: |
          export PYTHONPATH="src:packages/dotmac-platform-services/src"
          poetry run pytest tests/ -v --cov=src --cov-report=xml --cov-report=term --cov-report=html
        env:
          DATABASE_URL: postgresql://test_user:test_password@localhost:5432/test_db
          REDIS_URL: redis://localhost:6379/0
          ENVIRONMENT: test
          SKIP_OPENBAO_CHECKS: "true"
          SECRET_KEY: "test-secret-key-for-ci-only"
          JWT_SECRET: "test-jwt-secret-for-ci-only"
          ENCRYPTION_KEY: "test-encryption-key-for-ci-only-32-chars"
      
      - name: Generate coverage summary
        run: |
          echo "## 📊 Backend Test Coverage" >> $GITHUB_STEP_SUMMARY
          poetry run coverage report --format=markdown >> $GITHUB_STEP_SUMMARY
      
      - name: Coverage PR Comment
        if: github.event_name == 'pull_request'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          header: backend-coverage
          message: |
            ## 📊 Backend Test Coverage Report
            
            ```
            $(poetry run coverage report)
            ```
            
            📁 **Detailed HTML Report**: Available in workflow artifacts
      
      - name: Upload coverage artifacts
        uses: actions/upload-artifact@v4
        with:
          name: backend-coverage-${{ github.run_number }}
          path: |
            coverage.xml
            htmlcov/
          retention-days: 30

  # Frontend testing
  frontend:
    name: Frontend Tests
    runs-on: ubuntu-latest
    needs: [detect-changes]
    if: needs.detect-changes.outputs.frontend == 'true' || needs.detect-changes.outputs.shared == 'true'
    
    strategy:
      fail-fast: false
      matrix:
        include:
          - app: isp-framework/admin
            name: isp-admin
          - app: isp-framework/customer  
            name: isp-customer
          - app: isp-framework/reseller
            name: isp-reseller
          - app: management-portal/admin
            name: mgmt-admin
          - app: management-portal/tenant
            name: mgmt-tenant
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ${{ env.PNPM_VERSION }}
      
      - name: Cache pnpm dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.pnpm-store
            **/node_modules
          key: pnpm-${{ runner.os }}-${{ env.NODE_VERSION }}-${{ hashFiles('frontend/pnpm-lock.yaml') }}
          restore-keys: |
            pnpm-${{ runner.os }}-${{ env.NODE_VERSION }}-
      
      - name: Check if app exists
        id: check-app
        run: |
          if [ -d "./frontend/${{ matrix.app }}" ] && [ -f "./frontend/${{ matrix.app }}/package.json" ]; then
            echo "exists=true" >> $GITHUB_OUTPUT
            echo "✅ App ${{ matrix.app }} exists"
          else
            echo "exists=false" >> $GITHUB_OUTPUT
            echo "⚠️ App ${{ matrix.app }} does not exist, skipping"
          fi
      
      - name: Install dependencies
        if: steps.check-app.outputs.exists == 'true'
        run: pnpm install --frozen-lockfile
        working-directory: ./frontend
      
      - name: Type check and lint
        if: steps.check-app.outputs.exists == 'true'
        run: |
          if [ -f "package.json" ]; then
            if grep -q "type-check" package.json; then
              pnpm run type-check
            else
              echo "⚠️ No type-check script found, skipping"
            fi
            
            if grep -q "lint" package.json; then
              pnpm run lint
            else
              echo "⚠️ No lint script found, skipping"
            fi
          fi
        working-directory: ./frontend/${{ matrix.app }}
      
      - name: Run tests
        if: steps.check-app.outputs.exists == 'true'
        run: |
          if [ -f "package.json" ]; then
            if grep -q "test:unit\|test" package.json; then
              pnpm run test:unit --coverage 2>/dev/null || pnpm run test --coverage 2>/dev/null || echo "⚠️ No test script found or tests failed"
            else
              echo "⚠️ No test script found, skipping"
            fi
          fi
        working-directory: ./frontend/${{ matrix.app }}
      
      - name: Build
        if: steps.check-app.outputs.exists == 'true'
        run: |
          if [ -f "package.json" ]; then
            if grep -q "build" package.json; then
              pnpm run build
            else
              echo "⚠️ No build script found, skipping"
            fi
          fi
        working-directory: ./frontend/${{ matrix.app }}
      
      - name: Upload frontend coverage
        if: steps.check-app.outputs.exists == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: frontend-coverage-${{ matrix.name }}-${{ github.run_number }}
          path: |
            ./frontend/${{ matrix.app }}/coverage/
          retention-days: 30
        continue-on-error: true

  # Integration tests (only if both frontend and backend pass)
  integration:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: [backend, frontend]
    if: always() && (needs.backend.result == 'success' || needs.backend.result == 'skipped') && (needs.frontend.result == 'success' || needs.frontend.result == 'skipped')
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: test_password
          POSTGRES_USER: test_user
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      
      redis:
        image: redis:7
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ${{ env.PNPM_VERSION }}
      
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: latest
          virtualenvs-create: true
          virtualenvs-in-project: true
      
      - name: Install dependencies
        run: |
          # Backend
          poetry install --with dev,security
          
          # Frontend
          cd frontend && pnpm install --frozen-lockfile
      
      - name: Run comprehensive integration tests
        run: |
          echo "🧪 Running comprehensive test suite..."
          
          # Main framework tests
          if [ -d "tests" ]; then
            echo "Running main tests..."
            poetry run pytest tests/ -v --tb=short -x || echo "⚠️ Main tests had issues"
          fi
          
          # Package tests
          echo "Running package tests..."
          for package_dir in packages/*/; do
            if [ -d "${package_dir}" ] && [ -f "${package_dir}pyproject.toml" ]; then
              package_name=$(basename "${package_dir}")
              echo "Testing ${package_name}..."
              
              if [ -d "${package_dir}tests" ]; then
                cd "${package_dir}"
                if poetry run pytest tests/ -v --tb=short -x 2>/dev/null; then
                  echo "  ✅ ${package_name} tests passed"
                else
                  echo "  ⚠️ ${package_name} tests had issues"
                fi
                cd - > /dev/null
              else
                echo "  ⚠️ No tests found for ${package_name}"
              fi
            fi
          done
          
          # Integration tests if they exist
          for integration_dir in tests/integration tests/e2e integration_tests e2e_tests; do
            if [ -d "${integration_dir}" ]; then
              echo "Running ${integration_dir}..."
              poetry run pytest "${integration_dir}"/ -v --tb=short || echo "⚠️ ${integration_dir} had issues"
            fi
          done
          
          echo "✅ Integration test phase completed"
        env:
          DATABASE_URL: postgresql://test_user:test_password@localhost:5432/test_db
          REDIS_URL: redis://localhost:6379/0
          ENVIRONMENT: test
          SKIP_OPENBAO_CHECKS: "true"
          SECRET_KEY: "test-secret-key-for-ci-only"
          JWT_SECRET: "test-jwt-secret-for-ci-only"
          ENCRYPTION_KEY: "test-encryption-key-for-ci-only-32-chars"
          PYTHONPATH: "src:packages/dotmac-platform-services/src"
      
      - name: Upload E2E results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: frontend/playwright-report/
          retention-days: 7

  # Final status check
  ci-status:
    name: CI Status
    runs-on: ubuntu-latest
    needs: [security, backend, frontend, integration]
    if: always()
    
    steps:
      - name: Check results
        run: |
          echo "=== CI PIPELINE RESULTS ==="
          echo "Security: ${{ needs.security.result }}"
          echo "Backend: ${{ needs.backend.result }}"
          echo "Frontend: ${{ needs.frontend.result }}"
          echo "Integration: ${{ needs.integration.result }}"
          
          # Fail if critical jobs failed
          if [[ "${{ needs.security.result }}" == "failure" ]]; then
            echo "❌ Security checks failed"
            exit 1
          fi
          
          if [[ "${{ needs.backend.result }}" == "failure" ]]; then
            echo "❌ Backend tests failed"
            exit 1
          fi
          
          if [[ "${{ needs.frontend.result }}" == "failure" ]]; then
            echo "❌ Frontend tests failed"
            exit 1
          fi
          
          echo "✅ All critical checks passed"
