version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-dotmac_admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password123}
      POSTGRES_DB: dotmac_test
    ports:
      - "5439:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER:-dotmac_admin} -d dotmac_test"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks: [isp-ui]

  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD:-redis123}
    ports:
      - "6384:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD:-redis123}", "ping"]
    networks: [isp-ui]

  isp-service:
    build:
      context: ../../
      dockerfile: Dockerfile.isp
    environment:
      ENVIRONMENT: test
      LOG_LEVEL: INFO
      DATABASE_URL: postgresql+asyncpg://dotmac_admin:${POSTGRES_PASSWORD:-password123}@postgres:5432/dotmac_test
      REDIS_URL: redis://:${REDIS_PASSWORD:-redis123}@redis:6379/1
      PORT: 8001
      HOST: 0.0.0.0
      MANAGEMENT_PLATFORM_URL: ${MANAGEMENT_PLATFORM_URL:-}
    volumes:
      - ../../src/dotmac_isp:/app/src/dotmac_isp
      - ../../src/dotmac_shared:/app/src/dotmac_shared
      - ../../packages:/app/packages
    ports:
      - "8001:8001"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
    networks: [isp-ui]

  isp-admin-frontend:
    build:
      context: ../../frontend/isp-framework/admin
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: http://isp-service:8001
      PORT: 3000
      HOSTNAME: 0.0.0.0
    ports:
      - "3010:3000"
    depends_on:
      isp-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks: [isp-ui]

networks:
  isp-ui:
    driver: bridge
