apiVersion: v1
kind: ConfigMap
metadata:
  name: mgmt-platform-config
  namespace: dotmac-mgmt
  labels:
    app.kubernetes.io/name: dotmac-management-platform
    app.kubernetes.io/component: config
data:
  # Application configuration
  ENVIRONMENT: "production"
  LOG_LEVEL: "INFO"
  LOG_FORMAT: "json"
  
  # Database configuration
  DATABASE_POOL_SIZE: "20"
  DATABASE_MAX_OVERFLOW: "30"
  DATABASE_ECHO: "false"
  
  # Redis configuration  
  REDIS_MAX_CONNECTIONS: "100"
  
  # Celery configuration
  CELERY_WORKER_CONCURRENCY: "8"
  
  # API configuration
  API_V1_PREFIX: "/api/v1"
  DOCS_URL: ""  # Disable docs in production
  REDOC_URL: ""  # Disable redoc in production
  OPENAPI_URL: ""  # Disable openapi.json in production
  
  # Security configuration
  JWT_ALGORITHM: "HS256"
  ACCESS_TOKEN_EXPIRE_MINUTES: "30"
  REFRESH_TOKEN_EXPIRE_DAYS: "7"
  
  # Rate limiting
  RATE_LIMIT_ENABLED: "true"
  RATE_LIMIT_PER_MINUTE: "100"
  
  # Multi-tenant
  ENABLE_TENANT_ISOLATION: "true"
  MAX_TENANTS_PER_INSTANCE: "1000"
  DEFAULT_TENANT_TIER: "small"
  
  # Monitoring
  ENABLE_METRICS: "true"
  SIGNOZ_ENDPOINT: "signoz-collector:4317"
  
  # CORS
  CORS_ORIGINS: '["https://admin.dotmac.app", "https://tenant.dotmac.app", "https://reseller.dotmac.app"]'
  
  # External service endpoints
  STRIPE_TEST_MODE: "false"
  SENDGRID_FROM_EMAIL: "noreply@dotmac.app"
  AWS_REGION: "us-east-1"
  KUBERNETES_NAMESPACE_PREFIX: "dotmac-tenant"